// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DiscoveryService.proto

package com.lyl.skywalking.proto;

public interface ApplicationInstanceHeartbeatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApplicationInstanceHeartbeat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 applicationInstanceId = 1;</code>
   */
  int getApplicationInstanceId();

  /**
   * <code>optional int64 heartbeatTime = 2;</code>
   */
  long getHeartbeatTime();
}
