// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DiscoveryService.proto

package com.lyl.skywalking.proto;

/**
 * Protobuf type {@code ApplicationInstanceMapping}
 */
public  final class ApplicationInstanceMapping extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ApplicationInstanceMapping)
    ApplicationInstanceMappingOrBuilder {
  // Use ApplicationInstanceMapping.newBuilder() to construct.
  private ApplicationInstanceMapping(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ApplicationInstanceMapping() {
    applicationId_ = 0;
    applicationInstanceId_ = 0;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ApplicationInstanceMapping(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            applicationId_ = input.readInt32();
            break;
          }
          case 16: {

            applicationInstanceId_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lyl.skywalking.proto.DiscoveryService.internal_static_ApplicationInstanceMapping_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lyl.skywalking.proto.DiscoveryService.internal_static_ApplicationInstanceMapping_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lyl.skywalking.proto.ApplicationInstanceMapping.class, com.lyl.skywalking.proto.ApplicationInstanceMapping.Builder.class);
  }

  public static final int APPLICATIONID_FIELD_NUMBER = 1;
  private int applicationId_;
  /**
   * <code>optional int32 applicationId = 1;</code>
   */
  public int getApplicationId() {
    return applicationId_;
  }

  public static final int APPLICATIONINSTANCEID_FIELD_NUMBER = 2;
  private int applicationInstanceId_;
  /**
   * <code>optional int32 applicationInstanceId = 2;</code>
   */
  public int getApplicationInstanceId() {
    return applicationInstanceId_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (applicationId_ != 0) {
      output.writeInt32(1, applicationId_);
    }
    if (applicationInstanceId_ != 0) {
      output.writeInt32(2, applicationInstanceId_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (applicationId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, applicationId_);
    }
    if (applicationInstanceId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, applicationInstanceId_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.lyl.skywalking.proto.ApplicationInstanceMapping parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceMapping parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceMapping parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceMapping parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceMapping parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceMapping parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceMapping parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceMapping parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceMapping parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceMapping parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lyl.skywalking.proto.ApplicationInstanceMapping prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ApplicationInstanceMapping}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ApplicationInstanceMapping)
      com.lyl.skywalking.proto.ApplicationInstanceMappingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lyl.skywalking.proto.DiscoveryService.internal_static_ApplicationInstanceMapping_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lyl.skywalking.proto.DiscoveryService.internal_static_ApplicationInstanceMapping_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lyl.skywalking.proto.ApplicationInstanceMapping.class, com.lyl.skywalking.proto.ApplicationInstanceMapping.Builder.class);
    }

    // Construct using com.lyl.skywalking.proto.ApplicationInstanceMapping.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      applicationId_ = 0;

      applicationInstanceId_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lyl.skywalking.proto.DiscoveryService.internal_static_ApplicationInstanceMapping_descriptor;
    }

    public com.lyl.skywalking.proto.ApplicationInstanceMapping getDefaultInstanceForType() {
      return com.lyl.skywalking.proto.ApplicationInstanceMapping.getDefaultInstance();
    }

    public com.lyl.skywalking.proto.ApplicationInstanceMapping build() {
      com.lyl.skywalking.proto.ApplicationInstanceMapping result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.lyl.skywalking.proto.ApplicationInstanceMapping buildPartial() {
      com.lyl.skywalking.proto.ApplicationInstanceMapping result = new com.lyl.skywalking.proto.ApplicationInstanceMapping(this);
      result.applicationId_ = applicationId_;
      result.applicationInstanceId_ = applicationInstanceId_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lyl.skywalking.proto.ApplicationInstanceMapping) {
        return mergeFrom((com.lyl.skywalking.proto.ApplicationInstanceMapping)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lyl.skywalking.proto.ApplicationInstanceMapping other) {
      if (other == com.lyl.skywalking.proto.ApplicationInstanceMapping.getDefaultInstance()) return this;
      if (other.getApplicationId() != 0) {
        setApplicationId(other.getApplicationId());
      }
      if (other.getApplicationInstanceId() != 0) {
        setApplicationInstanceId(other.getApplicationInstanceId());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lyl.skywalking.proto.ApplicationInstanceMapping parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lyl.skywalking.proto.ApplicationInstanceMapping) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int applicationId_ ;
    /**
     * <code>optional int32 applicationId = 1;</code>
     */
    public int getApplicationId() {
      return applicationId_;
    }
    /**
     * <code>optional int32 applicationId = 1;</code>
     */
    public Builder setApplicationId(int value) {

      applicationId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 applicationId = 1;</code>
     */
    public Builder clearApplicationId() {

      applicationId_ = 0;
      onChanged();
      return this;
    }

    private int applicationInstanceId_ ;
    /**
     * <code>optional int32 applicationInstanceId = 2;</code>
     */
    public int getApplicationInstanceId() {
      return applicationInstanceId_;
    }
    /**
     * <code>optional int32 applicationInstanceId = 2;</code>
     */
    public Builder setApplicationInstanceId(int value) {

      applicationInstanceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 applicationInstanceId = 2;</code>
     */
    public Builder clearApplicationInstanceId() {

      applicationInstanceId_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:ApplicationInstanceMapping)
  }

  // @@protoc_insertion_point(class_scope:ApplicationInstanceMapping)
  private static final com.lyl.skywalking.proto.ApplicationInstanceMapping DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lyl.skywalking.proto.ApplicationInstanceMapping();
  }

  public static com.lyl.skywalking.proto.ApplicationInstanceMapping getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ApplicationInstanceMapping>
      PARSER = new com.google.protobuf.AbstractParser<ApplicationInstanceMapping>() {
    public ApplicationInstanceMapping parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new ApplicationInstanceMapping(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<ApplicationInstanceMapping> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ApplicationInstanceMapping> getParserForType() {
    return PARSER;
  }

  public com.lyl.skywalking.proto.ApplicationInstanceMapping getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

