// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ApplicationRegisterService.proto

package com.lyl.skywalking.proto;

public final class ApplicationRegisterServiceOuterClass {
  private ApplicationRegisterServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_Application_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Application_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ApplicationMapping_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ApplicationMapping_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n ApplicationRegisterService.proto\032\031KeyW" +
      "ithIntegerValue.proto\"&\n\013Application\022\027\n\017" +
      "applicationCode\030\001 \003(\t\"?\n\022ApplicationMapp" +
      "ing\022)\n\013application\030\001 \003(\0132\024.KeyWithIntege" +
      "rValue2M\n\032ApplicationRegisterService\022/\n\010" +
      "register\022\014.Application\032\023.ApplicationMapp" +
      "ing\"\000B\034\n\030com.lyl.skywalking.protoP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lyl.skywalking.proto.KeyWithIntegerValueOuterClass.getDescriptor(),
        }, assigner);
    internal_static_Application_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Application_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Application_descriptor,
        new String[] { "ApplicationCode", });
    internal_static_ApplicationMapping_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ApplicationMapping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ApplicationMapping_descriptor,
        new String[] { "Application", });
    com.lyl.skywalking.proto.KeyWithIntegerValueOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
