// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DiscoveryService.proto

package com.lyl.skywalking.proto;

public interface ApplicationInstanceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApplicationInstance)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 applicationId = 1;</code>
   */
  int getApplicationId();

  /**
   * <code>optional string agentUUID = 2;</code>
   */
  String getAgentUUID();
  /**
   * <code>optional string agentUUID = 2;</code>
   */
  com.google.protobuf.ByteString
      getAgentUUIDBytes();

  /**
   * <code>optional int64 registerTime = 3;</code>
   */
  long getRegisterTime();

  /**
   * <code>optional .OSInfo osinfo = 4;</code>
   */
  boolean hasOsinfo();
  /**
   * <code>optional .OSInfo osinfo = 4;</code>
   */
  com.lyl.skywalking.proto.OSInfo getOsinfo();
  /**
   * <code>optional .OSInfo osinfo = 4;</code>
   */
  com.lyl.skywalking.proto.OSInfoOrBuilder getOsinfoOrBuilder();
}
