// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DiscoveryService.proto

package com.lyl.skywalking.proto;

public interface ApplicationInstanceMappingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApplicationInstanceMapping)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 applicationId = 1;</code>
   */
  int getApplicationId();

  /**
   * <code>optional int32 applicationInstanceId = 2;</code>
   */
  int getApplicationInstanceId();
}
