// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DiscoveryService.proto

package com.lyl.skywalking.proto;

/**
 * Protobuf type {@code ApplicationInstanceHeartbeat}
 */
public  final class ApplicationInstanceHeartbeat extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ApplicationInstanceHeartbeat)
        ApplicationInstanceHeartbeatOrBuilder {
  // Use ApplicationInstanceHeartbeat.newBuilder() to construct.
  private ApplicationInstanceHeartbeat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ApplicationInstanceHeartbeat() {
    applicationInstanceId_ = 0;
    heartbeatTime_ = 0L;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ApplicationInstanceHeartbeat(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            applicationInstanceId_ = input.readInt32();
            break;
          }
          case 16: {

            heartbeatTime_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lyl.skywalking.proto.DiscoveryService.internal_static_ApplicationInstanceHeartbeat_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lyl.skywalking.proto.DiscoveryService.internal_static_ApplicationInstanceHeartbeat_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lyl.skywalking.proto.ApplicationInstanceHeartbeat.class, com.lyl.skywalking.proto.ApplicationInstanceHeartbeat.Builder.class);
  }

  public static final int APPLICATIONINSTANCEID_FIELD_NUMBER = 1;
  private int applicationInstanceId_;
  /**
   * <code>optional int32 applicationInstanceId = 1;</code>
   */
  public int getApplicationInstanceId() {
    return applicationInstanceId_;
  }

  public static final int HEARTBEATTIME_FIELD_NUMBER = 2;
  private long heartbeatTime_;
  /**
   * <code>optional int64 heartbeatTime = 2;</code>
   */
  public long getHeartbeatTime() {
    return heartbeatTime_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (applicationInstanceId_ != 0) {
      output.writeInt32(1, applicationInstanceId_);
    }
    if (heartbeatTime_ != 0L) {
      output.writeInt64(2, heartbeatTime_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (applicationInstanceId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, applicationInstanceId_);
    }
    if (heartbeatTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, heartbeatTime_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.lyl.skywalking.proto.ApplicationInstanceHeartbeat parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceHeartbeat parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceHeartbeat parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceHeartbeat parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceHeartbeat parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceHeartbeat parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceHeartbeat parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceHeartbeat parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceHeartbeat parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceHeartbeat parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lyl.skywalking.proto.ApplicationInstanceHeartbeat prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ApplicationInstanceHeartbeat}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ApplicationInstanceHeartbeat)
      com.lyl.skywalking.proto.ApplicationInstanceHeartbeatOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lyl.skywalking.proto.DiscoveryService.internal_static_ApplicationInstanceHeartbeat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lyl.skywalking.proto.DiscoveryService.internal_static_ApplicationInstanceHeartbeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lyl.skywalking.proto.ApplicationInstanceHeartbeat.class, com.lyl.skywalking.proto.ApplicationInstanceHeartbeat.Builder.class);
    }

    // Construct using com.lyl.skywalking.proto.ApplicationInstanceHeartbeat.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      applicationInstanceId_ = 0;

      heartbeatTime_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lyl.skywalking.proto.DiscoveryService.internal_static_ApplicationInstanceHeartbeat_descriptor;
    }

    public com.lyl.skywalking.proto.ApplicationInstanceHeartbeat getDefaultInstanceForType() {
      return com.lyl.skywalking.proto.ApplicationInstanceHeartbeat.getDefaultInstance();
    }

    public com.lyl.skywalking.proto.ApplicationInstanceHeartbeat build() {
      com.lyl.skywalking.proto.ApplicationInstanceHeartbeat result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.lyl.skywalking.proto.ApplicationInstanceHeartbeat buildPartial() {
      com.lyl.skywalking.proto.ApplicationInstanceHeartbeat result = new com.lyl.skywalking.proto.ApplicationInstanceHeartbeat(this);
      result.applicationInstanceId_ = applicationInstanceId_;
      result.heartbeatTime_ = heartbeatTime_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lyl.skywalking.proto.ApplicationInstanceHeartbeat) {
        return mergeFrom((com.lyl.skywalking.proto.ApplicationInstanceHeartbeat)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lyl.skywalking.proto.ApplicationInstanceHeartbeat other) {
      if (other == com.lyl.skywalking.proto.ApplicationInstanceHeartbeat.getDefaultInstance()) return this;
      if (other.getApplicationInstanceId() != 0) {
        setApplicationInstanceId(other.getApplicationInstanceId());
      }
      if (other.getHeartbeatTime() != 0L) {
        setHeartbeatTime(other.getHeartbeatTime());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lyl.skywalking.proto.ApplicationInstanceHeartbeat parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lyl.skywalking.proto.ApplicationInstanceHeartbeat) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int applicationInstanceId_ ;
    /**
     * <code>optional int32 applicationInstanceId = 1;</code>
     */
    public int getApplicationInstanceId() {
      return applicationInstanceId_;
    }
    /**
     * <code>optional int32 applicationInstanceId = 1;</code>
     */
    public Builder setApplicationInstanceId(int value) {

      applicationInstanceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 applicationInstanceId = 1;</code>
     */
    public Builder clearApplicationInstanceId() {

      applicationInstanceId_ = 0;
      onChanged();
      return this;
    }

    private long heartbeatTime_ ;
    /**
     * <code>optional int64 heartbeatTime = 2;</code>
     */
    public long getHeartbeatTime() {
      return heartbeatTime_;
    }
    /**
     * <code>optional int64 heartbeatTime = 2;</code>
     */
    public Builder setHeartbeatTime(long value) {

      heartbeatTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 heartbeatTime = 2;</code>
     */
    public Builder clearHeartbeatTime() {

      heartbeatTime_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:ApplicationInstanceHeartbeat)
  }

  // @@protoc_insertion_point(class_scope:ApplicationInstanceHeartbeat)
  private static final com.lyl.skywalking.proto.ApplicationInstanceHeartbeat DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lyl.skywalking.proto.ApplicationInstanceHeartbeat();
  }

  public static com.lyl.skywalking.proto.ApplicationInstanceHeartbeat getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ApplicationInstanceHeartbeat>
      PARSER = new com.google.protobuf.AbstractParser<ApplicationInstanceHeartbeat>() {
    public ApplicationInstanceHeartbeat parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new ApplicationInstanceHeartbeat(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<ApplicationInstanceHeartbeat> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ApplicationInstanceHeartbeat> getParserForType() {
    return PARSER;
  }

  public com.lyl.skywalking.proto.ApplicationInstanceHeartbeat getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

