// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DiscoveryService.proto

package com.lyl.skywalking.proto;

/**
 * Protobuf type {@code ApplicationInstanceRecover}
 */
public  final class ApplicationInstanceRecover extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ApplicationInstanceRecover)
        ApplicationInstanceRecoverOrBuilder {
  // Use ApplicationInstanceRecover.newBuilder() to construct.
  private ApplicationInstanceRecover(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ApplicationInstanceRecover() {
    applicationId_ = 0;
    applicationInstanceId_ = 0;
    registerTime_ = 0L;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ApplicationInstanceRecover(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            applicationId_ = input.readInt32();
            break;
          }
          case 16: {

            applicationInstanceId_ = input.readInt32();
            break;
          }
          case 24: {

            registerTime_ = input.readInt64();
            break;
          }
          case 34: {
            com.lyl.skywalking.proto.OSInfo.Builder subBuilder = null;
            if (osinfo_ != null) {
              subBuilder = osinfo_.toBuilder();
            }
            osinfo_ = input.readMessage(com.lyl.skywalking.proto.OSInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(osinfo_);
              osinfo_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lyl.skywalking.proto.DiscoveryService.internal_static_ApplicationInstanceRecover_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lyl.skywalking.proto.DiscoveryService.internal_static_ApplicationInstanceRecover_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lyl.skywalking.proto.ApplicationInstanceRecover.class, com.lyl.skywalking.proto.ApplicationInstanceRecover.Builder.class);
  }

  public static final int APPLICATIONID_FIELD_NUMBER = 1;
  private int applicationId_;
  /**
   * <code>optional int32 applicationId = 1;</code>
   */
  public int getApplicationId() {
    return applicationId_;
  }

  public static final int APPLICATIONINSTANCEID_FIELD_NUMBER = 2;
  private int applicationInstanceId_;
  /**
   * <code>optional int32 applicationInstanceId = 2;</code>
   */
  public int getApplicationInstanceId() {
    return applicationInstanceId_;
  }

  public static final int REGISTERTIME_FIELD_NUMBER = 3;
  private long registerTime_;
  /**
   * <code>optional int64 registerTime = 3;</code>
   */
  public long getRegisterTime() {
    return registerTime_;
  }

  public static final int OSINFO_FIELD_NUMBER = 4;
  private com.lyl.skywalking.proto.OSInfo osinfo_;
  /**
   * <code>optional .OSInfo osinfo = 4;</code>
   */
  public boolean hasOsinfo() {
    return osinfo_ != null;
  }
  /**
   * <code>optional .OSInfo osinfo = 4;</code>
   */
  public com.lyl.skywalking.proto.OSInfo getOsinfo() {
    return osinfo_ == null ? com.lyl.skywalking.proto.OSInfo.getDefaultInstance() : osinfo_;
  }
  /**
   * <code>optional .OSInfo osinfo = 4;</code>
   */
  public com.lyl.skywalking.proto.OSInfoOrBuilder getOsinfoOrBuilder() {
    return getOsinfo();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (applicationId_ != 0) {
      output.writeInt32(1, applicationId_);
    }
    if (applicationInstanceId_ != 0) {
      output.writeInt32(2, applicationInstanceId_);
    }
    if (registerTime_ != 0L) {
      output.writeInt64(3, registerTime_);
    }
    if (osinfo_ != null) {
      output.writeMessage(4, getOsinfo());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (applicationId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, applicationId_);
    }
    if (applicationInstanceId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, applicationInstanceId_);
    }
    if (registerTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, registerTime_);
    }
    if (osinfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getOsinfo());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.lyl.skywalking.proto.ApplicationInstanceRecover parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceRecover parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceRecover parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceRecover parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceRecover parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceRecover parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceRecover parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceRecover parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceRecover parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.lyl.skywalking.proto.ApplicationInstanceRecover parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lyl.skywalking.proto.ApplicationInstanceRecover prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ApplicationInstanceRecover}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ApplicationInstanceRecover)
      com.lyl.skywalking.proto.ApplicationInstanceRecoverOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lyl.skywalking.proto.DiscoveryService.internal_static_ApplicationInstanceRecover_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lyl.skywalking.proto.DiscoveryService.internal_static_ApplicationInstanceRecover_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lyl.skywalking.proto.ApplicationInstanceRecover.class, com.lyl.skywalking.proto.ApplicationInstanceRecover.Builder.class);
    }

    // Construct using com.lyl.skywalking.proto.ApplicationInstanceRecover.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      applicationId_ = 0;

      applicationInstanceId_ = 0;

      registerTime_ = 0L;

      if (osinfoBuilder_ == null) {
        osinfo_ = null;
      } else {
        osinfo_ = null;
        osinfoBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lyl.skywalking.proto.DiscoveryService.internal_static_ApplicationInstanceRecover_descriptor;
    }

    public com.lyl.skywalking.proto.ApplicationInstanceRecover getDefaultInstanceForType() {
      return com.lyl.skywalking.proto.ApplicationInstanceRecover.getDefaultInstance();
    }

    public com.lyl.skywalking.proto.ApplicationInstanceRecover build() {
      com.lyl.skywalking.proto.ApplicationInstanceRecover result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.lyl.skywalking.proto.ApplicationInstanceRecover buildPartial() {
      com.lyl.skywalking.proto.ApplicationInstanceRecover result = new com.lyl.skywalking.proto.ApplicationInstanceRecover(this);
      result.applicationId_ = applicationId_;
      result.applicationInstanceId_ = applicationInstanceId_;
      result.registerTime_ = registerTime_;
      if (osinfoBuilder_ == null) {
        result.osinfo_ = osinfo_;
      } else {
        result.osinfo_ = osinfoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lyl.skywalking.proto.ApplicationInstanceRecover) {
        return mergeFrom((com.lyl.skywalking.proto.ApplicationInstanceRecover)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lyl.skywalking.proto.ApplicationInstanceRecover other) {
      if (other == com.lyl.skywalking.proto.ApplicationInstanceRecover.getDefaultInstance()) return this;
      if (other.getApplicationId() != 0) {
        setApplicationId(other.getApplicationId());
      }
      if (other.getApplicationInstanceId() != 0) {
        setApplicationInstanceId(other.getApplicationInstanceId());
      }
      if (other.getRegisterTime() != 0L) {
        setRegisterTime(other.getRegisterTime());
      }
      if (other.hasOsinfo()) {
        mergeOsinfo(other.getOsinfo());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lyl.skywalking.proto.ApplicationInstanceRecover parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lyl.skywalking.proto.ApplicationInstanceRecover) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int applicationId_ ;
    /**
     * <code>optional int32 applicationId = 1;</code>
     */
    public int getApplicationId() {
      return applicationId_;
    }
    /**
     * <code>optional int32 applicationId = 1;</code>
     */
    public Builder setApplicationId(int value) {

      applicationId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 applicationId = 1;</code>
     */
    public Builder clearApplicationId() {

      applicationId_ = 0;
      onChanged();
      return this;
    }

    private int applicationInstanceId_ ;
    /**
     * <code>optional int32 applicationInstanceId = 2;</code>
     */
    public int getApplicationInstanceId() {
      return applicationInstanceId_;
    }
    /**
     * <code>optional int32 applicationInstanceId = 2;</code>
     */
    public Builder setApplicationInstanceId(int value) {

      applicationInstanceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 applicationInstanceId = 2;</code>
     */
    public Builder clearApplicationInstanceId() {

      applicationInstanceId_ = 0;
      onChanged();
      return this;
    }

    private long registerTime_ ;
    /**
     * <code>optional int64 registerTime = 3;</code>
     */
    public long getRegisterTime() {
      return registerTime_;
    }
    /**
     * <code>optional int64 registerTime = 3;</code>
     */
    public Builder setRegisterTime(long value) {

      registerTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 registerTime = 3;</code>
     */
    public Builder clearRegisterTime() {

      registerTime_ = 0L;
      onChanged();
      return this;
    }

    private com.lyl.skywalking.proto.OSInfo osinfo_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        com.lyl.skywalking.proto.OSInfo, com.lyl.skywalking.proto.OSInfo.Builder, com.lyl.skywalking.proto.OSInfoOrBuilder> osinfoBuilder_;
    /**
     * <code>optional .OSInfo osinfo = 4;</code>
     */
    public boolean hasOsinfo() {
      return osinfoBuilder_ != null || osinfo_ != null;
    }
    /**
     * <code>optional .OSInfo osinfo = 4;</code>
     */
    public com.lyl.skywalking.proto.OSInfo getOsinfo() {
      if (osinfoBuilder_ == null) {
        return osinfo_ == null ? com.lyl.skywalking.proto.OSInfo.getDefaultInstance() : osinfo_;
      } else {
        return osinfoBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .OSInfo osinfo = 4;</code>
     */
    public Builder setOsinfo(com.lyl.skywalking.proto.OSInfo value) {
      if (osinfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        osinfo_ = value;
        onChanged();
      } else {
        osinfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .OSInfo osinfo = 4;</code>
     */
    public Builder setOsinfo(
        com.lyl.skywalking.proto.OSInfo.Builder builderForValue) {
      if (osinfoBuilder_ == null) {
        osinfo_ = builderForValue.build();
        onChanged();
      } else {
        osinfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .OSInfo osinfo = 4;</code>
     */
    public Builder mergeOsinfo(com.lyl.skywalking.proto.OSInfo value) {
      if (osinfoBuilder_ == null) {
        if (osinfo_ != null) {
          osinfo_ =
            com.lyl.skywalking.proto.OSInfo.newBuilder(osinfo_).mergeFrom(value).buildPartial();
        } else {
          osinfo_ = value;
        }
        onChanged();
      } else {
        osinfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .OSInfo osinfo = 4;</code>
     */
    public Builder clearOsinfo() {
      if (osinfoBuilder_ == null) {
        osinfo_ = null;
        onChanged();
      } else {
        osinfo_ = null;
        osinfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .OSInfo osinfo = 4;</code>
     */
    public com.lyl.skywalking.proto.OSInfo.Builder getOsinfoBuilder() {

      onChanged();
      return getOsinfoFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .OSInfo osinfo = 4;</code>
     */
    public com.lyl.skywalking.proto.OSInfoOrBuilder getOsinfoOrBuilder() {
      if (osinfoBuilder_ != null) {
        return osinfoBuilder_.getMessageOrBuilder();
      } else {
        return osinfo_ == null ?
            com.lyl.skywalking.proto.OSInfo.getDefaultInstance() : osinfo_;
      }
    }
    /**
     * <code>optional .OSInfo osinfo = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.lyl.skywalking.proto.OSInfo, com.lyl.skywalking.proto.OSInfo.Builder, com.lyl.skywalking.proto.OSInfoOrBuilder>
        getOsinfoFieldBuilder() {
      if (osinfoBuilder_ == null) {
        osinfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.lyl.skywalking.proto.OSInfo, com.lyl.skywalking.proto.OSInfo.Builder, com.lyl.skywalking.proto.OSInfoOrBuilder>(
                getOsinfo(),
                getParentForChildren(),
                isClean());
        osinfo_ = null;
      }
      return osinfoBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:ApplicationInstanceRecover)
  }

  // @@protoc_insertion_point(class_scope:ApplicationInstanceRecover)
  private static final com.lyl.skywalking.proto.ApplicationInstanceRecover DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lyl.skywalking.proto.ApplicationInstanceRecover();
  }

  public static com.lyl.skywalking.proto.ApplicationInstanceRecover getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ApplicationInstanceRecover>
      PARSER = new com.google.protobuf.AbstractParser<ApplicationInstanceRecover>() {
    public ApplicationInstanceRecover parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new ApplicationInstanceRecover(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<ApplicationInstanceRecover> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ApplicationInstanceRecover> getParserForType() {
    return PARSER;
  }

  public com.lyl.skywalking.proto.ApplicationInstanceRecover getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

