// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JVMMetricsService.proto

package com.lyl.skywalking.proto;

public interface CPUOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CPU)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional double usagePercent = 2;</code>
   */
  double getUsagePercent();
}
