// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DiscoveryService.proto

package com.lyl.skywalking.proto;

public final class DiscoveryService {
  private DiscoveryService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ApplicationInstance_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ApplicationInstance_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ApplicationInstanceMapping_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ApplicationInstanceMapping_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ApplicationInstanceRecover_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ApplicationInstanceRecover_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ApplicationInstanceHeartbeat_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ApplicationInstanceHeartbeat_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_OSInfo_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OSInfo_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceNameCollection_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ServiceNameCollection_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceNameMappingCollection_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ServiceNameMappingCollection_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceNameMappingElement_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ServiceNameMappingElement_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceNameElement_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ServiceNameElement_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026DiscoveryService.proto\032\020Downstream.pro" +
      "to\"n\n\023ApplicationInstance\022\025\n\rapplication" +
      "Id\030\001 \001(\005\022\021\n\tagentUUID\030\002 \001(\t\022\024\n\014registerT" +
      "ime\030\003 \001(\003\022\027\n\006osinfo\030\004 \001(\0132\007.OSInfo\"R\n\032Ap" +
      "plicationInstanceMapping\022\025\n\rapplicationI" +
      "d\030\001 \001(\005\022\035\n\025applicationInstanceId\030\002 \001(\005\"\201" +
      "\001\n\032ApplicationInstanceRecover\022\025\n\rapplica" +
      "tionId\030\001 \001(\005\022\035\n\025applicationInstanceId\030\002 " +
      "\001(\005\022\024\n\014registerTime\030\003 \001(\003\022\027\n\006osinfo\030\004 \001(" +
      "\0132\007.OSInfo\"T\n\034ApplicationInstanceHeartbe",
      "at\022\035\n\025applicationInstanceId\030\001 \001(\005\022\025\n\rhea" +
      "rtbeatTime\030\002 \001(\003\"L\n\006OSInfo\022\016\n\006osName\030\001 \001" +
      "(\t\022\020\n\010hostname\030\002 \001(\t\022\021\n\tprocessNo\030\003 \001(\005\022" +
      "\r\n\005ipv4s\030\004 \003(\t\">\n\025ServiceNameCollection\022" +
      "%\n\010elements\030\001 \003(\0132\023.ServiceNameElement\"L" +
      "\n\034ServiceNameMappingCollection\022,\n\010elemen" +
      "ts\030\001 \003(\0132\032.ServiceNameMappingElement\"T\n\031" +
      "ServiceNameMappingElement\022\021\n\tserviceId\030\001" +
      " \001(\005\022$\n\007element\030\002 \001(\0132\023.ServiceNameEleme" +
      "nt\"@\n\022ServiceNameElement\022\023\n\013serviceName\030",
      "\001 \001(\t\022\025\n\rapplicationId\030\002 \001(\0052\325\001\n\030Instanc" +
      "eDiscoveryService\022?\n\010register\022\024.Applicat" +
      "ionInstance\032\033.ApplicationInstanceMapping" +
      "\"\000\0229\n\theartbeat\022\035.ApplicationInstanceHea" +
      "rtbeat\032\013.Downstream\"\000\022=\n\017registerRecover" +
      "\022\033.ApplicationInstanceRecover\032\013.Downstre" +
      "am\"\0002c\n\033ServiceNameDiscoveryService\022D\n\td" +
      "iscovery\022\026.ServiceNameCollection\032\035.Servi" +
      "ceNameMappingCollection\"\000B\034\n\030com.lyl.sky" +
      "walking.protoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lyl.skywalking.proto.DownstreamOuterClass.getDescriptor(),
        }, assigner);
    internal_static_ApplicationInstance_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ApplicationInstance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ApplicationInstance_descriptor,
        new String[] { "ApplicationId", "AgentUUID", "RegisterTime", "Osinfo", });
    internal_static_ApplicationInstanceMapping_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ApplicationInstanceMapping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ApplicationInstanceMapping_descriptor,
        new String[] { "ApplicationId", "ApplicationInstanceId", });
    internal_static_ApplicationInstanceRecover_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ApplicationInstanceRecover_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ApplicationInstanceRecover_descriptor,
        new String[] { "ApplicationId", "ApplicationInstanceId", "RegisterTime", "Osinfo", });
    internal_static_ApplicationInstanceHeartbeat_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ApplicationInstanceHeartbeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ApplicationInstanceHeartbeat_descriptor,
        new String[] { "ApplicationInstanceId", "HeartbeatTime", });
    internal_static_OSInfo_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_OSInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_OSInfo_descriptor,
        new String[] { "OsName", "Hostname", "ProcessNo", "Ipv4S", });
    internal_static_ServiceNameCollection_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ServiceNameCollection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ServiceNameCollection_descriptor,
        new String[] { "Elements", });
    internal_static_ServiceNameMappingCollection_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ServiceNameMappingCollection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ServiceNameMappingCollection_descriptor,
        new String[] { "Elements", });
    internal_static_ServiceNameMappingElement_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ServiceNameMappingElement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ServiceNameMappingElement_descriptor,
        new String[] { "ServiceId", "Element", });
    internal_static_ServiceNameElement_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_ServiceNameElement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ServiceNameElement_descriptor,
        new String[] { "ServiceName", "ApplicationId", });
    com.lyl.skywalking.proto.DownstreamOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
