// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Downstream.proto

package com.lyl.skywalking.proto;

public interface DownstreamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Downstream)
    com.google.protobuf.MessageOrBuilder {
}
