// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JVMMetricsService.proto

package com.lyl.skywalking.proto;

/**
 * Protobuf type {@code GC}
 */
public  final class GC extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:GC)
        GCOrBuilder {
  // Use GC.newBuilder() to construct.
  private GC(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GC() {
    phrase_ = 0;
    count_ = 0L;
    time_ = 0L;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private GC(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            phrase_ = rawValue;
            break;
          }
          case 16: {

            count_ = input.readInt64();
            break;
          }
          case 24: {

            time_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lyl.skywalking.proto.JVMMetricsServiceOuterClass.internal_static_GC_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lyl.skywalking.proto.JVMMetricsServiceOuterClass.internal_static_GC_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lyl.skywalking.proto.GC.class, com.lyl.skywalking.proto.GC.Builder.class);
  }

  public static final int PHRASE_FIELD_NUMBER = 1;
  private int phrase_;
  /**
   * <code>optional .GCPhrase phrase = 1;</code>
   */
  public int getPhraseValue() {
    return phrase_;
  }
  /**
   * <code>optional .GCPhrase phrase = 1;</code>
   */
  public com.lyl.skywalking.proto.GCPhrase getPhrase() {
    com.lyl.skywalking.proto.GCPhrase result = com.lyl.skywalking.proto.GCPhrase.valueOf(phrase_);
    return result == null ? com.lyl.skywalking.proto.GCPhrase.UNRECOGNIZED : result;
  }

  public static final int COUNT_FIELD_NUMBER = 2;
  private long count_;
  /**
   * <code>optional int64 count = 2;</code>
   */
  public long getCount() {
    return count_;
  }

  public static final int TIME_FIELD_NUMBER = 3;
  private long time_;
  /**
   * <code>optional int64 time = 3;</code>
   */
  public long getTime() {
    return time_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (phrase_ != com.lyl.skywalking.proto.GCPhrase.NEW.getNumber()) {
      output.writeEnum(1, phrase_);
    }
    if (count_ != 0L) {
      output.writeInt64(2, count_);
    }
    if (time_ != 0L) {
      output.writeInt64(3, time_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (phrase_ != com.lyl.skywalking.proto.GCPhrase.NEW.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, phrase_);
    }
    if (count_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, count_);
    }
    if (time_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, time_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.lyl.skywalking.proto.GC parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lyl.skywalking.proto.GC parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.GC parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lyl.skywalking.proto.GC parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.GC parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.lyl.skywalking.proto.GC parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.GC parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.lyl.skywalking.proto.GC parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.GC parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.lyl.skywalking.proto.GC parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lyl.skywalking.proto.GC prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GC}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GC)
      com.lyl.skywalking.proto.GCOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lyl.skywalking.proto.JVMMetricsServiceOuterClass.internal_static_GC_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lyl.skywalking.proto.JVMMetricsServiceOuterClass.internal_static_GC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lyl.skywalking.proto.GC.class, com.lyl.skywalking.proto.GC.Builder.class);
    }

    // Construct using com.lyl.skywalking.proto.GC.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      phrase_ = 0;

      count_ = 0L;

      time_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lyl.skywalking.proto.JVMMetricsServiceOuterClass.internal_static_GC_descriptor;
    }

    public com.lyl.skywalking.proto.GC getDefaultInstanceForType() {
      return com.lyl.skywalking.proto.GC.getDefaultInstance();
    }

    public com.lyl.skywalking.proto.GC build() {
      com.lyl.skywalking.proto.GC result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.lyl.skywalking.proto.GC buildPartial() {
      com.lyl.skywalking.proto.GC result = new com.lyl.skywalking.proto.GC(this);
      result.phrase_ = phrase_;
      result.count_ = count_;
      result.time_ = time_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lyl.skywalking.proto.GC) {
        return mergeFrom((com.lyl.skywalking.proto.GC)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lyl.skywalking.proto.GC other) {
      if (other == com.lyl.skywalking.proto.GC.getDefaultInstance()) return this;
      if (other.phrase_ != 0) {
        setPhraseValue(other.getPhraseValue());
      }
      if (other.getCount() != 0L) {
        setCount(other.getCount());
      }
      if (other.getTime() != 0L) {
        setTime(other.getTime());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lyl.skywalking.proto.GC parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lyl.skywalking.proto.GC) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int phrase_ = 0;
    /**
     * <code>optional .GCPhrase phrase = 1;</code>
     */
    public int getPhraseValue() {
      return phrase_;
    }
    /**
     * <code>optional .GCPhrase phrase = 1;</code>
     */
    public Builder setPhraseValue(int value) {
      phrase_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .GCPhrase phrase = 1;</code>
     */
    public com.lyl.skywalking.proto.GCPhrase getPhrase() {
      com.lyl.skywalking.proto.GCPhrase result = com.lyl.skywalking.proto.GCPhrase.valueOf(phrase_);
      return result == null ? com.lyl.skywalking.proto.GCPhrase.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .GCPhrase phrase = 1;</code>
     */
    public Builder setPhrase(com.lyl.skywalking.proto.GCPhrase value) {
      if (value == null) {
        throw new NullPointerException();
      }

      phrase_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .GCPhrase phrase = 1;</code>
     */
    public Builder clearPhrase() {

      phrase_ = 0;
      onChanged();
      return this;
    }

    private long count_ ;
    /**
     * <code>optional int64 count = 2;</code>
     */
    public long getCount() {
      return count_;
    }
    /**
     * <code>optional int64 count = 2;</code>
     */
    public Builder setCount(long value) {

      count_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 count = 2;</code>
     */
    public Builder clearCount() {

      count_ = 0L;
      onChanged();
      return this;
    }

    private long time_ ;
    /**
     * <code>optional int64 time = 3;</code>
     */
    public long getTime() {
      return time_;
    }
    /**
     * <code>optional int64 time = 3;</code>
     */
    public Builder setTime(long value) {

      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 time = 3;</code>
     */
    public Builder clearTime() {

      time_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:GC)
  }

  // @@protoc_insertion_point(class_scope:GC)
  private static final com.lyl.skywalking.proto.GC DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lyl.skywalking.proto.GC();
  }

  public static com.lyl.skywalking.proto.GC getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GC>
      PARSER = new com.google.protobuf.AbstractParser<GC>() {
    public GC parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new GC(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<GC> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<GC> getParserForType() {
    return PARSER;
  }

  public com.lyl.skywalking.proto.GC getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

