// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JVMMetricsService.proto

package com.lyl.skywalking.proto;

public interface GCOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GC)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .GCPhrase phrase = 1;</code>
   */
  int getPhraseValue();
  /**
   * <code>optional .GCPhrase phrase = 1;</code>
   */
  com.lyl.skywalking.proto.GCPhrase getPhrase();

  /**
   * <code>optional int64 count = 2;</code>
   */
  long getCount();

  /**
   * <code>optional int64 time = 3;</code>
   */
  long getTime();
}
