// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JVMMetricsService.proto

package com.lyl.skywalking.proto;

/**
 * Protobuf enum {@code GCPhrase}
 */
public enum GCPhrase
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>NEW = 0;</code>
   */
  NEW(0, 0),
  /**
   * <code>OLD = 1;</code>
   */
  OLD(1, 1),
  UNRECOGNIZED(-1, -1),
  ;

  /**
   * <code>NEW = 0;</code>
   */
  public static final int NEW_VALUE = 0;
  /**
   * <code>OLD = 1;</code>
   */
  public static final int OLD_VALUE = 1;


  public final int getNumber() {
    if (index == -1) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  public static GCPhrase valueOf(int value) {
    switch (value) {
      case 0: return NEW;
      case 1: return OLD;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<GCPhrase>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
          GCPhrase> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<GCPhrase>() {
          public GCPhrase findValueByNumber(int number) {
            return GCPhrase.valueOf(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(index);
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.lyl.skywalking.proto.JVMMetricsServiceOuterClass.getDescriptor()
        .getEnumTypes().get(1);
  }

  private static final GCPhrase[] VALUES = values();

  public static GCPhrase valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int index;
  private final int value;

  private GCPhrase(int index, int value) {
    this.index = index;
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:GCPhrase)
}

