// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JVMMetricsService.proto

package com.lyl.skywalking.proto;

/**
 * Protobuf type {@code JVMMetrics}
 */
public  final class JVMMetrics extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:JVMMetrics)
    JVMMetricsOrBuilder {
  // Use JVMMetrics.newBuilder() to construct.
  private JVMMetrics(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private JVMMetrics() {
    metrics_ = java.util.Collections.emptyList();
    applicationInstanceId_ = 0;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private JVMMetrics(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              metrics_ = new java.util.ArrayList<JVMMetric>();
              mutable_bitField0_ |= 0x00000001;
            }
            metrics_.add(input.readMessage(com.lyl.skywalking.proto.JVMMetric.parser(), extensionRegistry));
            break;
          }
          case 16: {

            applicationInstanceId_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        metrics_ = java.util.Collections.unmodifiableList(metrics_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lyl.skywalking.proto.JVMMetricsServiceOuterClass.internal_static_JVMMetrics_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lyl.skywalking.proto.JVMMetricsServiceOuterClass.internal_static_JVMMetrics_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lyl.skywalking.proto.JVMMetrics.class, com.lyl.skywalking.proto.JVMMetrics.Builder.class);
  }

  private int bitField0_;
  public static final int METRICS_FIELD_NUMBER = 1;
  private java.util.List<JVMMetric> metrics_;
  /**
   * <code>repeated .JVMMetric metrics = 1;</code>
   */
  public java.util.List<JVMMetric> getMetricsList() {
    return metrics_;
  }
  /**
   * <code>repeated .JVMMetric metrics = 1;</code>
   */
  public java.util.List<? extends com.lyl.skywalking.proto.JVMMetricOrBuilder>
      getMetricsOrBuilderList() {
    return metrics_;
  }
  /**
   * <code>repeated .JVMMetric metrics = 1;</code>
   */
  public int getMetricsCount() {
    return metrics_.size();
  }
  /**
   * <code>repeated .JVMMetric metrics = 1;</code>
   */
  public com.lyl.skywalking.proto.JVMMetric getMetrics(int index) {
    return metrics_.get(index);
  }
  /**
   * <code>repeated .JVMMetric metrics = 1;</code>
   */
  public com.lyl.skywalking.proto.JVMMetricOrBuilder getMetricsOrBuilder(
      int index) {
    return metrics_.get(index);
  }

  public static final int APPLICATIONINSTANCEID_FIELD_NUMBER = 2;
  private int applicationInstanceId_;
  /**
   * <code>optional int32 applicationInstanceId = 2;</code>
   */
  public int getApplicationInstanceId() {
    return applicationInstanceId_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < metrics_.size(); i++) {
      output.writeMessage(1, metrics_.get(i));
    }
    if (applicationInstanceId_ != 0) {
      output.writeInt32(2, applicationInstanceId_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < metrics_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, metrics_.get(i));
    }
    if (applicationInstanceId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, applicationInstanceId_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.lyl.skywalking.proto.JVMMetrics parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lyl.skywalking.proto.JVMMetrics parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.JVMMetrics parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lyl.skywalking.proto.JVMMetrics parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.JVMMetrics parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.lyl.skywalking.proto.JVMMetrics parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.JVMMetrics parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.lyl.skywalking.proto.JVMMetrics parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.JVMMetrics parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.lyl.skywalking.proto.JVMMetrics parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lyl.skywalking.proto.JVMMetrics prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code JVMMetrics}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:JVMMetrics)
      com.lyl.skywalking.proto.JVMMetricsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lyl.skywalking.proto.JVMMetricsServiceOuterClass.internal_static_JVMMetrics_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lyl.skywalking.proto.JVMMetricsServiceOuterClass.internal_static_JVMMetrics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lyl.skywalking.proto.JVMMetrics.class, com.lyl.skywalking.proto.JVMMetrics.Builder.class);
    }

    // Construct using com.lyl.skywalking.proto.JVMMetrics.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getMetricsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (metricsBuilder_ == null) {
        metrics_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        metricsBuilder_.clear();
      }
      applicationInstanceId_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lyl.skywalking.proto.JVMMetricsServiceOuterClass.internal_static_JVMMetrics_descriptor;
    }

    public com.lyl.skywalking.proto.JVMMetrics getDefaultInstanceForType() {
      return com.lyl.skywalking.proto.JVMMetrics.getDefaultInstance();
    }

    public com.lyl.skywalking.proto.JVMMetrics build() {
      com.lyl.skywalking.proto.JVMMetrics result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.lyl.skywalking.proto.JVMMetrics buildPartial() {
      com.lyl.skywalking.proto.JVMMetrics result = new com.lyl.skywalking.proto.JVMMetrics(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (metricsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          metrics_ = java.util.Collections.unmodifiableList(metrics_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.metrics_ = metrics_;
      } else {
        result.metrics_ = metricsBuilder_.build();
      }
      result.applicationInstanceId_ = applicationInstanceId_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lyl.skywalking.proto.JVMMetrics) {
        return mergeFrom((com.lyl.skywalking.proto.JVMMetrics)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lyl.skywalking.proto.JVMMetrics other) {
      if (other == com.lyl.skywalking.proto.JVMMetrics.getDefaultInstance()) return this;
      if (metricsBuilder_ == null) {
        if (!other.metrics_.isEmpty()) {
          if (metrics_.isEmpty()) {
            metrics_ = other.metrics_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMetricsIsMutable();
            metrics_.addAll(other.metrics_);
          }
          onChanged();
        }
      } else {
        if (!other.metrics_.isEmpty()) {
          if (metricsBuilder_.isEmpty()) {
            metricsBuilder_.dispose();
            metricsBuilder_ = null;
            metrics_ = other.metrics_;
            bitField0_ = (bitField0_ & ~0x00000001);
            metricsBuilder_ =
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getMetricsFieldBuilder() : null;
          } else {
            metricsBuilder_.addAllMessages(other.metrics_);
          }
        }
      }
      if (other.getApplicationInstanceId() != 0) {
        setApplicationInstanceId(other.getApplicationInstanceId());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lyl.skywalking.proto.JVMMetrics parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lyl.skywalking.proto.JVMMetrics) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<JVMMetric> metrics_ =
      java.util.Collections.emptyList();
    private void ensureMetricsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        metrics_ = new java.util.ArrayList<JVMMetric>(metrics_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.lyl.skywalking.proto.JVMMetric, com.lyl.skywalking.proto.JVMMetric.Builder, com.lyl.skywalking.proto.JVMMetricOrBuilder> metricsBuilder_;

    /**
     * <code>repeated .JVMMetric metrics = 1;</code>
     */
    public java.util.List<JVMMetric> getMetricsList() {
      if (metricsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(metrics_);
      } else {
        return metricsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .JVMMetric metrics = 1;</code>
     */
    public int getMetricsCount() {
      if (metricsBuilder_ == null) {
        return metrics_.size();
      } else {
        return metricsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .JVMMetric metrics = 1;</code>
     */
    public com.lyl.skywalking.proto.JVMMetric getMetrics(int index) {
      if (metricsBuilder_ == null) {
        return metrics_.get(index);
      } else {
        return metricsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .JVMMetric metrics = 1;</code>
     */
    public Builder setMetrics(
        int index, com.lyl.skywalking.proto.JVMMetric value) {
      if (metricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetricsIsMutable();
        metrics_.set(index, value);
        onChanged();
      } else {
        metricsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .JVMMetric metrics = 1;</code>
     */
    public Builder setMetrics(
        int index, com.lyl.skywalking.proto.JVMMetric.Builder builderForValue) {
      if (metricsBuilder_ == null) {
        ensureMetricsIsMutable();
        metrics_.set(index, builderForValue.build());
        onChanged();
      } else {
        metricsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .JVMMetric metrics = 1;</code>
     */
    public Builder addMetrics(com.lyl.skywalking.proto.JVMMetric value) {
      if (metricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetricsIsMutable();
        metrics_.add(value);
        onChanged();
      } else {
        metricsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .JVMMetric metrics = 1;</code>
     */
    public Builder addMetrics(
        int index, com.lyl.skywalking.proto.JVMMetric value) {
      if (metricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetricsIsMutable();
        metrics_.add(index, value);
        onChanged();
      } else {
        metricsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .JVMMetric metrics = 1;</code>
     */
    public Builder addMetrics(
        com.lyl.skywalking.proto.JVMMetric.Builder builderForValue) {
      if (metricsBuilder_ == null) {
        ensureMetricsIsMutable();
        metrics_.add(builderForValue.build());
        onChanged();
      } else {
        metricsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .JVMMetric metrics = 1;</code>
     */
    public Builder addMetrics(
        int index, com.lyl.skywalking.proto.JVMMetric.Builder builderForValue) {
      if (metricsBuilder_ == null) {
        ensureMetricsIsMutable();
        metrics_.add(index, builderForValue.build());
        onChanged();
      } else {
        metricsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .JVMMetric metrics = 1;</code>
     */
    public Builder addAllMetrics(
        Iterable<? extends JVMMetric> values) {
      if (metricsBuilder_ == null) {
        ensureMetricsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, metrics_);
        onChanged();
      } else {
        metricsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .JVMMetric metrics = 1;</code>
     */
    public Builder clearMetrics() {
      if (metricsBuilder_ == null) {
        metrics_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        metricsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .JVMMetric metrics = 1;</code>
     */
    public Builder removeMetrics(int index) {
      if (metricsBuilder_ == null) {
        ensureMetricsIsMutable();
        metrics_.remove(index);
        onChanged();
      } else {
        metricsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .JVMMetric metrics = 1;</code>
     */
    public com.lyl.skywalking.proto.JVMMetric.Builder getMetricsBuilder(
        int index) {
      return getMetricsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .JVMMetric metrics = 1;</code>
     */
    public com.lyl.skywalking.proto.JVMMetricOrBuilder getMetricsOrBuilder(
        int index) {
      if (metricsBuilder_ == null) {
        return metrics_.get(index);  } else {
        return metricsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .JVMMetric metrics = 1;</code>
     */
    public java.util.List<? extends com.lyl.skywalking.proto.JVMMetricOrBuilder>
         getMetricsOrBuilderList() {
      if (metricsBuilder_ != null) {
        return metricsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(metrics_);
      }
    }
    /**
     * <code>repeated .JVMMetric metrics = 1;</code>
     */
    public com.lyl.skywalking.proto.JVMMetric.Builder addMetricsBuilder() {
      return getMetricsFieldBuilder().addBuilder(
          com.lyl.skywalking.proto.JVMMetric.getDefaultInstance());
    }
    /**
     * <code>repeated .JVMMetric metrics = 1;</code>
     */
    public com.lyl.skywalking.proto.JVMMetric.Builder addMetricsBuilder(
        int index) {
      return getMetricsFieldBuilder().addBuilder(
          index, com.lyl.skywalking.proto.JVMMetric.getDefaultInstance());
    }
    /**
     * <code>repeated .JVMMetric metrics = 1;</code>
     */
    public java.util.List<JVMMetric.Builder>
         getMetricsBuilderList() {
      return getMetricsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.lyl.skywalking.proto.JVMMetric, com.lyl.skywalking.proto.JVMMetric.Builder, com.lyl.skywalking.proto.JVMMetricOrBuilder>
        getMetricsFieldBuilder() {
      if (metricsBuilder_ == null) {
        metricsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.lyl.skywalking.proto.JVMMetric, com.lyl.skywalking.proto.JVMMetric.Builder, com.lyl.skywalking.proto.JVMMetricOrBuilder>(
                metrics_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        metrics_ = null;
      }
      return metricsBuilder_;
    }

    private int applicationInstanceId_ ;
    /**
     * <code>optional int32 applicationInstanceId = 2;</code>
     */
    public int getApplicationInstanceId() {
      return applicationInstanceId_;
    }
    /**
     * <code>optional int32 applicationInstanceId = 2;</code>
     */
    public Builder setApplicationInstanceId(int value) {

      applicationInstanceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 applicationInstanceId = 2;</code>
     */
    public Builder clearApplicationInstanceId() {

      applicationInstanceId_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:JVMMetrics)
  }

  // @@protoc_insertion_point(class_scope:JVMMetrics)
  private static final com.lyl.skywalking.proto.JVMMetrics DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lyl.skywalking.proto.JVMMetrics();
  }

  public static com.lyl.skywalking.proto.JVMMetrics getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JVMMetrics>
      PARSER = new com.google.protobuf.AbstractParser<JVMMetrics>() {
    public JVMMetrics parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new JVMMetrics(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<JVMMetrics> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<JVMMetrics> getParserForType() {
    return PARSER;
  }

  public com.lyl.skywalking.proto.JVMMetrics getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

