// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JVMMetricsService.proto

package com.lyl.skywalking.proto;

public interface JVMMetricsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:JVMMetrics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .JVMMetric metrics = 1;</code>
   */
  java.util.List<JVMMetric>
      getMetricsList();
  /**
   * <code>repeated .JVMMetric metrics = 1;</code>
   */
  com.lyl.skywalking.proto.JVMMetric getMetrics(int index);
  /**
   * <code>repeated .JVMMetric metrics = 1;</code>
   */
  int getMetricsCount();
  /**
   * <code>repeated .JVMMetric metrics = 1;</code>
   */
  java.util.List<? extends JVMMetricOrBuilder>
      getMetricsOrBuilderList();
  /**
   * <code>repeated .JVMMetric metrics = 1;</code>
   */
  com.lyl.skywalking.proto.JVMMetricOrBuilder getMetricsOrBuilder(
          int index);

  /**
   * <code>optional int32 applicationInstanceId = 2;</code>
   */
  int getApplicationInstanceId();
}
