// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KeyWithIntegerValue.proto

package com.lyl.skywalking.proto;

public interface KeyWithIntegerValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:KeyWithIntegerValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string key = 1;</code>
   */
  String getKey();
  /**
   * <code>optional string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>optional int32 value = 2;</code>
   */
  int getValue();
}
