// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KeyWithStringValue.proto

package com.lyl.skywalking.proto;

public interface KeyWithStringValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:KeyWithStringValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string key = 1;</code>
   */
  String getKey();
  /**
   * <code>optional string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>optional string value = 2;</code>
   */
  String getValue();
  /**
   * <code>optional string value = 2;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
