// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KeyWithIntegerValue.proto

package com.lyl.skywalking.proto;

public final class KeyWithIntegerValueOuterClass {
  private KeyWithIntegerValueOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_KeyWithIntegerValue_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_KeyWithIntegerValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\031KeyWithIntegerValue.proto\"1\n\023KeyWithIn" +
      "tegerValue\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\005B\034" +
      "\n\030com.lyl.skywalking.protoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_KeyWithIntegerValue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_KeyWithIntegerValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_KeyWithIntegerValue_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
