// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JVMMetricsService.proto

package com.lyl.skywalking.proto;

public interface MemoryPoolOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MemoryPool)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .PoolType type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>optional .PoolType type = 1;</code>
   */
  com.lyl.skywalking.proto.PoolType getType();

  /**
   * <code>optional int64 init = 2;</code>
   */
  long getInit();

  /**
   * <code>optional int64 max = 3;</code>
   */
  long getMax();

  /**
   * <code>optional int64 used = 4;</code>
   */
  long getUsed();

  /**
   * <code>optional int64 commited = 5;</code>
   */
  long getCommited();
}
