// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JVMMetricsService.proto

package com.lyl.skywalking.proto;

/**
 * Protobuf type {@code Memory}
 */
public  final class Memory extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Memory)
        MemoryOrBuilder {
  // Use Memory.newBuilder() to construct.
  private Memory(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Memory() {
    isHeap_ = false;
    init_ = 0L;
    max_ = 0L;
    used_ = 0L;
    committed_ = 0L;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Memory(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            isHeap_ = input.readBool();
            break;
          }
          case 16: {

            init_ = input.readInt64();
            break;
          }
          case 24: {

            max_ = input.readInt64();
            break;
          }
          case 32: {

            used_ = input.readInt64();
            break;
          }
          case 40: {

            committed_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lyl.skywalking.proto.JVMMetricsServiceOuterClass.internal_static_Memory_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lyl.skywalking.proto.JVMMetricsServiceOuterClass.internal_static_Memory_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lyl.skywalking.proto.Memory.class, com.lyl.skywalking.proto.Memory.Builder.class);
  }

  public static final int ISHEAP_FIELD_NUMBER = 1;
  private boolean isHeap_;
  /**
   * <code>optional bool isHeap = 1;</code>
   */
  public boolean getIsHeap() {
    return isHeap_;
  }

  public static final int INIT_FIELD_NUMBER = 2;
  private long init_;
  /**
   * <code>optional int64 init = 2;</code>
   */
  public long getInit() {
    return init_;
  }

  public static final int MAX_FIELD_NUMBER = 3;
  private long max_;
  /**
   * <code>optional int64 max = 3;</code>
   */
  public long getMax() {
    return max_;
  }

  public static final int USED_FIELD_NUMBER = 4;
  private long used_;
  /**
   * <code>optional int64 used = 4;</code>
   */
  public long getUsed() {
    return used_;
  }

  public static final int COMMITTED_FIELD_NUMBER = 5;
  private long committed_;
  /**
   * <code>optional int64 committed = 5;</code>
   */
  public long getCommitted() {
    return committed_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isHeap_ != false) {
      output.writeBool(1, isHeap_);
    }
    if (init_ != 0L) {
      output.writeInt64(2, init_);
    }
    if (max_ != 0L) {
      output.writeInt64(3, max_);
    }
    if (used_ != 0L) {
      output.writeInt64(4, used_);
    }
    if (committed_ != 0L) {
      output.writeInt64(5, committed_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isHeap_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isHeap_);
    }
    if (init_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, init_);
    }
    if (max_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, max_);
    }
    if (used_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, used_);
    }
    if (committed_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, committed_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.lyl.skywalking.proto.Memory parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lyl.skywalking.proto.Memory parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.Memory parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lyl.skywalking.proto.Memory parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.Memory parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.lyl.skywalking.proto.Memory parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.Memory parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.lyl.skywalking.proto.Memory parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.Memory parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.lyl.skywalking.proto.Memory parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lyl.skywalking.proto.Memory prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Memory}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Memory)
      com.lyl.skywalking.proto.MemoryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lyl.skywalking.proto.JVMMetricsServiceOuterClass.internal_static_Memory_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lyl.skywalking.proto.JVMMetricsServiceOuterClass.internal_static_Memory_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lyl.skywalking.proto.Memory.class, com.lyl.skywalking.proto.Memory.Builder.class);
    }

    // Construct using com.lyl.skywalking.proto.Memory.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      isHeap_ = false;

      init_ = 0L;

      max_ = 0L;

      used_ = 0L;

      committed_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lyl.skywalking.proto.JVMMetricsServiceOuterClass.internal_static_Memory_descriptor;
    }

    public com.lyl.skywalking.proto.Memory getDefaultInstanceForType() {
      return com.lyl.skywalking.proto.Memory.getDefaultInstance();
    }

    public com.lyl.skywalking.proto.Memory build() {
      com.lyl.skywalking.proto.Memory result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.lyl.skywalking.proto.Memory buildPartial() {
      com.lyl.skywalking.proto.Memory result = new com.lyl.skywalking.proto.Memory(this);
      result.isHeap_ = isHeap_;
      result.init_ = init_;
      result.max_ = max_;
      result.used_ = used_;
      result.committed_ = committed_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lyl.skywalking.proto.Memory) {
        return mergeFrom((com.lyl.skywalking.proto.Memory)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lyl.skywalking.proto.Memory other) {
      if (other == com.lyl.skywalking.proto.Memory.getDefaultInstance()) return this;
      if (other.getIsHeap() != false) {
        setIsHeap(other.getIsHeap());
      }
      if (other.getInit() != 0L) {
        setInit(other.getInit());
      }
      if (other.getMax() != 0L) {
        setMax(other.getMax());
      }
      if (other.getUsed() != 0L) {
        setUsed(other.getUsed());
      }
      if (other.getCommitted() != 0L) {
        setCommitted(other.getCommitted());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lyl.skywalking.proto.Memory parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lyl.skywalking.proto.Memory) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean isHeap_ ;
    /**
     * <code>optional bool isHeap = 1;</code>
     */
    public boolean getIsHeap() {
      return isHeap_;
    }
    /**
     * <code>optional bool isHeap = 1;</code>
     */
    public Builder setIsHeap(boolean value) {

      isHeap_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool isHeap = 1;</code>
     */
    public Builder clearIsHeap() {

      isHeap_ = false;
      onChanged();
      return this;
    }

    private long init_ ;
    /**
     * <code>optional int64 init = 2;</code>
     */
    public long getInit() {
      return init_;
    }
    /**
     * <code>optional int64 init = 2;</code>
     */
    public Builder setInit(long value) {

      init_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 init = 2;</code>
     */
    public Builder clearInit() {

      init_ = 0L;
      onChanged();
      return this;
    }

    private long max_ ;
    /**
     * <code>optional int64 max = 3;</code>
     */
    public long getMax() {
      return max_;
    }
    /**
     * <code>optional int64 max = 3;</code>
     */
    public Builder setMax(long value) {

      max_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 max = 3;</code>
     */
    public Builder clearMax() {

      max_ = 0L;
      onChanged();
      return this;
    }

    private long used_ ;
    /**
     * <code>optional int64 used = 4;</code>
     */
    public long getUsed() {
      return used_;
    }
    /**
     * <code>optional int64 used = 4;</code>
     */
    public Builder setUsed(long value) {

      used_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 used = 4;</code>
     */
    public Builder clearUsed() {

      used_ = 0L;
      onChanged();
      return this;
    }

    private long committed_ ;
    /**
     * <code>optional int64 committed = 5;</code>
     */
    public long getCommitted() {
      return committed_;
    }
    /**
     * <code>optional int64 committed = 5;</code>
     */
    public Builder setCommitted(long value) {

      committed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 committed = 5;</code>
     */
    public Builder clearCommitted() {

      committed_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:Memory)
  }

  // @@protoc_insertion_point(class_scope:Memory)
  private static final com.lyl.skywalking.proto.Memory DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lyl.skywalking.proto.Memory();
  }

  public static com.lyl.skywalking.proto.Memory getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Memory>
      PARSER = new com.google.protobuf.AbstractParser<Memory>() {
    public Memory parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new Memory(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<Memory> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Memory> getParserForType() {
    return PARSER;
  }

  public com.lyl.skywalking.proto.Memory getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

