// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DiscoveryService.proto

package com.lyl.skywalking.proto;

public interface OSInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OSInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string osName = 1;</code>
   */
  String getOsName();
  /**
   * <code>optional string osName = 1;</code>
   */
  com.google.protobuf.ByteString
      getOsNameBytes();

  /**
   * <code>optional string hostname = 2;</code>
   */
  String getHostname();
  /**
   * <code>optional string hostname = 2;</code>
   */
  com.google.protobuf.ByteString
      getHostnameBytes();

  /**
   * <code>optional int32 processNo = 3;</code>
   */
  int getProcessNo();

  /**
   * <code>repeated string ipv4s = 4;</code>
   */
  com.google.protobuf.ProtocolStringList
      getIpv4SList();
  /**
   * <code>repeated string ipv4s = 4;</code>
   */
  int getIpv4SCount();
  /**
   * <code>repeated string ipv4s = 4;</code>
   */
  String getIpv4S(int index);
  /**
   * <code>repeated string ipv4s = 4;</code>
   */
  com.google.protobuf.ByteString
      getIpv4SBytes(int index);
}
