// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DiscoveryService.proto

package com.lyl.skywalking.proto;

/**
 * Protobuf type {@code OSInfo}
 */
public  final class OSInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:OSInfo)
        OSInfoOrBuilder {
  // Use OSInfo.newBuilder() to construct.
  private OSInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private OSInfo() {
    osName_ = "";
    hostname_ = "";
    processNo_ = 0;
    ipv4S_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private OSInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            osName_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            hostname_ = s;
            break;
          }
          case 24: {

            processNo_ = input.readInt32();
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              ipv4S_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000008;
            }
            ipv4S_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        ipv4S_ = ipv4S_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lyl.skywalking.proto.DiscoveryService.internal_static_OSInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lyl.skywalking.proto.DiscoveryService.internal_static_OSInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lyl.skywalking.proto.OSInfo.class, com.lyl.skywalking.proto.OSInfo.Builder.class);
  }

  private int bitField0_;
  public static final int OSNAME_FIELD_NUMBER = 1;
  private volatile Object osName_;
  /**
   * <code>optional string osName = 1;</code>
   */
  public String getOsName() {
    Object ref = osName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      osName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string osName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getOsNameBytes() {
    Object ref = osName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      osName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HOSTNAME_FIELD_NUMBER = 2;
  private volatile Object hostname_;
  /**
   * <code>optional string hostname = 2;</code>
   */
  public String getHostname() {
    Object ref = hostname_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      hostname_ = s;
      return s;
    }
  }
  /**
   * <code>optional string hostname = 2;</code>
   */
  public com.google.protobuf.ByteString
      getHostnameBytes() {
    Object ref = hostname_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      hostname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROCESSNO_FIELD_NUMBER = 3;
  private int processNo_;
  /**
   * <code>optional int32 processNo = 3;</code>
   */
  public int getProcessNo() {
    return processNo_;
  }

  public static final int IPV4S_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList ipv4S_;
  /**
   * <code>repeated string ipv4s = 4;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getIpv4SList() {
    return ipv4S_;
  }
  /**
   * <code>repeated string ipv4s = 4;</code>
   */
  public int getIpv4SCount() {
    return ipv4S_.size();
  }
  /**
   * <code>repeated string ipv4s = 4;</code>
   */
  public String getIpv4S(int index) {
    return ipv4S_.get(index);
  }
  /**
   * <code>repeated string ipv4s = 4;</code>
   */
  public com.google.protobuf.ByteString
      getIpv4SBytes(int index) {
    return ipv4S_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getOsNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, osName_);
    }
    if (!getHostnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, hostname_);
    }
    if (processNo_ != 0) {
      output.writeInt32(3, processNo_);
    }
    for (int i = 0; i < ipv4S_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, ipv4S_.getRaw(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getOsNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, osName_);
    }
    if (!getHostnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, hostname_);
    }
    if (processNo_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, processNo_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < ipv4S_.size(); i++) {
        dataSize += computeStringSizeNoTag(ipv4S_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getIpv4SList().size();
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.lyl.skywalking.proto.OSInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lyl.skywalking.proto.OSInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.OSInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lyl.skywalking.proto.OSInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.OSInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.lyl.skywalking.proto.OSInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.OSInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.lyl.skywalking.proto.OSInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.OSInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.lyl.skywalking.proto.OSInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lyl.skywalking.proto.OSInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code OSInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:OSInfo)
      com.lyl.skywalking.proto.OSInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lyl.skywalking.proto.DiscoveryService.internal_static_OSInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lyl.skywalking.proto.DiscoveryService.internal_static_OSInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lyl.skywalking.proto.OSInfo.class, com.lyl.skywalking.proto.OSInfo.Builder.class);
    }

    // Construct using com.lyl.skywalking.proto.OSInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      osName_ = "";

      hostname_ = "";

      processNo_ = 0;

      ipv4S_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lyl.skywalking.proto.DiscoveryService.internal_static_OSInfo_descriptor;
    }

    public com.lyl.skywalking.proto.OSInfo getDefaultInstanceForType() {
      return com.lyl.skywalking.proto.OSInfo.getDefaultInstance();
    }

    public com.lyl.skywalking.proto.OSInfo build() {
      com.lyl.skywalking.proto.OSInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.lyl.skywalking.proto.OSInfo buildPartial() {
      com.lyl.skywalking.proto.OSInfo result = new com.lyl.skywalking.proto.OSInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.osName_ = osName_;
      result.hostname_ = hostname_;
      result.processNo_ = processNo_;
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        ipv4S_ = ipv4S_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.ipv4S_ = ipv4S_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lyl.skywalking.proto.OSInfo) {
        return mergeFrom((com.lyl.skywalking.proto.OSInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lyl.skywalking.proto.OSInfo other) {
      if (other == com.lyl.skywalking.proto.OSInfo.getDefaultInstance()) return this;
      if (!other.getOsName().isEmpty()) {
        osName_ = other.osName_;
        onChanged();
      }
      if (!other.getHostname().isEmpty()) {
        hostname_ = other.hostname_;
        onChanged();
      }
      if (other.getProcessNo() != 0) {
        setProcessNo(other.getProcessNo());
      }
      if (!other.ipv4S_.isEmpty()) {
        if (ipv4S_.isEmpty()) {
          ipv4S_ = other.ipv4S_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureIpv4SIsMutable();
          ipv4S_.addAll(other.ipv4S_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lyl.skywalking.proto.OSInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lyl.skywalking.proto.OSInfo) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object osName_ = "";
    /**
     * <code>optional string osName = 1;</code>
     */
    public String getOsName() {
      Object ref = osName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        osName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string osName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOsNameBytes() {
      Object ref = osName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        osName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string osName = 1;</code>
     */
    public Builder setOsName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      osName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string osName = 1;</code>
     */
    public Builder clearOsName() {

      osName_ = getDefaultInstance().getOsName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string osName = 1;</code>
     */
    public Builder setOsNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      osName_ = value;
      onChanged();
      return this;
    }

    private Object hostname_ = "";
    /**
     * <code>optional string hostname = 2;</code>
     */
    public String getHostname() {
      Object ref = hostname_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        hostname_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string hostname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHostnameBytes() {
      Object ref = hostname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        hostname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string hostname = 2;</code>
     */
    public Builder setHostname(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      hostname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string hostname = 2;</code>
     */
    public Builder clearHostname() {

      hostname_ = getDefaultInstance().getHostname();
      onChanged();
      return this;
    }
    /**
     * <code>optional string hostname = 2;</code>
     */
    public Builder setHostnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      hostname_ = value;
      onChanged();
      return this;
    }

    private int processNo_ ;
    /**
     * <code>optional int32 processNo = 3;</code>
     */
    public int getProcessNo() {
      return processNo_;
    }
    /**
     * <code>optional int32 processNo = 3;</code>
     */
    public Builder setProcessNo(int value) {

      processNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 processNo = 3;</code>
     */
    public Builder clearProcessNo() {

      processNo_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList ipv4S_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureIpv4SIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        ipv4S_ = new com.google.protobuf.LazyStringArrayList(ipv4S_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <code>repeated string ipv4s = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getIpv4SList() {
      return ipv4S_.getUnmodifiableView();
    }
    /**
     * <code>repeated string ipv4s = 4;</code>
     */
    public int getIpv4SCount() {
      return ipv4S_.size();
    }
    /**
     * <code>repeated string ipv4s = 4;</code>
     */
    public String getIpv4S(int index) {
      return ipv4S_.get(index);
    }
    /**
     * <code>repeated string ipv4s = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIpv4SBytes(int index) {
      return ipv4S_.getByteString(index);
    }
    /**
     * <code>repeated string ipv4s = 4;</code>
     */
    public Builder setIpv4S(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureIpv4SIsMutable();
      ipv4S_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string ipv4s = 4;</code>
     */
    public Builder addIpv4S(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureIpv4SIsMutable();
      ipv4S_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string ipv4s = 4;</code>
     */
    public Builder addAllIpv4S(
        Iterable<String> values) {
      ensureIpv4SIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, ipv4S_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string ipv4s = 4;</code>
     */
    public Builder clearIpv4S() {
      ipv4S_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string ipv4s = 4;</code>
     */
    public Builder addIpv4SBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureIpv4SIsMutable();
      ipv4S_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:OSInfo)
  }

  // @@protoc_insertion_point(class_scope:OSInfo)
  private static final com.lyl.skywalking.proto.OSInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lyl.skywalking.proto.OSInfo();
  }

  public static com.lyl.skywalking.proto.OSInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OSInfo>
      PARSER = new com.google.protobuf.AbstractParser<OSInfo>() {
    public OSInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new OSInfo(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<OSInfo> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<OSInfo> getParserForType() {
    return PARSER;
  }

  public com.lyl.skywalking.proto.OSInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

