// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DiscoveryService.proto

package com.lyl.skywalking.proto;

/**
 * Protobuf type {@code ServiceNameMappingElement}
 */
public  final class ServiceNameMappingElement extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ServiceNameMappingElement)
    ServiceNameMappingElementOrBuilder {
  // Use ServiceNameMappingElement.newBuilder() to construct.
  private ServiceNameMappingElement(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ServiceNameMappingElement() {
    serviceId_ = 0;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ServiceNameMappingElement(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            serviceId_ = input.readInt32();
            break;
          }
          case 18: {
            com.lyl.skywalking.proto.ServiceNameElement.Builder subBuilder = null;
            if (element_ != null) {
              subBuilder = element_.toBuilder();
            }
            element_ = input.readMessage(com.lyl.skywalking.proto.ServiceNameElement.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(element_);
              element_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lyl.skywalking.proto.DiscoveryService.internal_static_ServiceNameMappingElement_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lyl.skywalking.proto.DiscoveryService.internal_static_ServiceNameMappingElement_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lyl.skywalking.proto.ServiceNameMappingElement.class, com.lyl.skywalking.proto.ServiceNameMappingElement.Builder.class);
  }

  public static final int SERVICEID_FIELD_NUMBER = 1;
  private int serviceId_;
  /**
   * <code>optional int32 serviceId = 1;</code>
   */
  public int getServiceId() {
    return serviceId_;
  }

  public static final int ELEMENT_FIELD_NUMBER = 2;
  private com.lyl.skywalking.proto.ServiceNameElement element_;
  /**
   * <code>optional .ServiceNameElement element = 2;</code>
   */
  public boolean hasElement() {
    return element_ != null;
  }
  /**
   * <code>optional .ServiceNameElement element = 2;</code>
   */
  public com.lyl.skywalking.proto.ServiceNameElement getElement() {
    return element_ == null ? com.lyl.skywalking.proto.ServiceNameElement.getDefaultInstance() : element_;
  }
  /**
   * <code>optional .ServiceNameElement element = 2;</code>
   */
  public com.lyl.skywalking.proto.ServiceNameElementOrBuilder getElementOrBuilder() {
    return getElement();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (serviceId_ != 0) {
      output.writeInt32(1, serviceId_);
    }
    if (element_ != null) {
      output.writeMessage(2, getElement());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (serviceId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, serviceId_);
    }
    if (element_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getElement());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.lyl.skywalking.proto.ServiceNameMappingElement parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lyl.skywalking.proto.ServiceNameMappingElement parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.ServiceNameMappingElement parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lyl.skywalking.proto.ServiceNameMappingElement parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.ServiceNameMappingElement parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.lyl.skywalking.proto.ServiceNameMappingElement parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.ServiceNameMappingElement parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.lyl.skywalking.proto.ServiceNameMappingElement parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.ServiceNameMappingElement parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.lyl.skywalking.proto.ServiceNameMappingElement parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lyl.skywalking.proto.ServiceNameMappingElement prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ServiceNameMappingElement}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ServiceNameMappingElement)
      com.lyl.skywalking.proto.ServiceNameMappingElementOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lyl.skywalking.proto.DiscoveryService.internal_static_ServiceNameMappingElement_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lyl.skywalking.proto.DiscoveryService.internal_static_ServiceNameMappingElement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lyl.skywalking.proto.ServiceNameMappingElement.class, com.lyl.skywalking.proto.ServiceNameMappingElement.Builder.class);
    }

    // Construct using com.lyl.skywalking.proto.ServiceNameMappingElement.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      serviceId_ = 0;

      if (elementBuilder_ == null) {
        element_ = null;
      } else {
        element_ = null;
        elementBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lyl.skywalking.proto.DiscoveryService.internal_static_ServiceNameMappingElement_descriptor;
    }

    public com.lyl.skywalking.proto.ServiceNameMappingElement getDefaultInstanceForType() {
      return com.lyl.skywalking.proto.ServiceNameMappingElement.getDefaultInstance();
    }

    public com.lyl.skywalking.proto.ServiceNameMappingElement build() {
      com.lyl.skywalking.proto.ServiceNameMappingElement result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.lyl.skywalking.proto.ServiceNameMappingElement buildPartial() {
      com.lyl.skywalking.proto.ServiceNameMappingElement result = new com.lyl.skywalking.proto.ServiceNameMappingElement(this);
      result.serviceId_ = serviceId_;
      if (elementBuilder_ == null) {
        result.element_ = element_;
      } else {
        result.element_ = elementBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lyl.skywalking.proto.ServiceNameMappingElement) {
        return mergeFrom((com.lyl.skywalking.proto.ServiceNameMappingElement)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lyl.skywalking.proto.ServiceNameMappingElement other) {
      if (other == com.lyl.skywalking.proto.ServiceNameMappingElement.getDefaultInstance()) return this;
      if (other.getServiceId() != 0) {
        setServiceId(other.getServiceId());
      }
      if (other.hasElement()) {
        mergeElement(other.getElement());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lyl.skywalking.proto.ServiceNameMappingElement parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lyl.skywalking.proto.ServiceNameMappingElement) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int serviceId_ ;
    /**
     * <code>optional int32 serviceId = 1;</code>
     */
    public int getServiceId() {
      return serviceId_;
    }
    /**
     * <code>optional int32 serviceId = 1;</code>
     */
    public Builder setServiceId(int value) {

      serviceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 serviceId = 1;</code>
     */
    public Builder clearServiceId() {

      serviceId_ = 0;
      onChanged();
      return this;
    }

    private com.lyl.skywalking.proto.ServiceNameElement element_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        com.lyl.skywalking.proto.ServiceNameElement, com.lyl.skywalking.proto.ServiceNameElement.Builder, com.lyl.skywalking.proto.ServiceNameElementOrBuilder> elementBuilder_;
    /**
     * <code>optional .ServiceNameElement element = 2;</code>
     */
    public boolean hasElement() {
      return elementBuilder_ != null || element_ != null;
    }
    /**
     * <code>optional .ServiceNameElement element = 2;</code>
     */
    public com.lyl.skywalking.proto.ServiceNameElement getElement() {
      if (elementBuilder_ == null) {
        return element_ == null ? com.lyl.skywalking.proto.ServiceNameElement.getDefaultInstance() : element_;
      } else {
        return elementBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .ServiceNameElement element = 2;</code>
     */
    public Builder setElement(com.lyl.skywalking.proto.ServiceNameElement value) {
      if (elementBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        element_ = value;
        onChanged();
      } else {
        elementBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .ServiceNameElement element = 2;</code>
     */
    public Builder setElement(
        com.lyl.skywalking.proto.ServiceNameElement.Builder builderForValue) {
      if (elementBuilder_ == null) {
        element_ = builderForValue.build();
        onChanged();
      } else {
        elementBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .ServiceNameElement element = 2;</code>
     */
    public Builder mergeElement(com.lyl.skywalking.proto.ServiceNameElement value) {
      if (elementBuilder_ == null) {
        if (element_ != null) {
          element_ =
            com.lyl.skywalking.proto.ServiceNameElement.newBuilder(element_).mergeFrom(value).buildPartial();
        } else {
          element_ = value;
        }
        onChanged();
      } else {
        elementBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .ServiceNameElement element = 2;</code>
     */
    public Builder clearElement() {
      if (elementBuilder_ == null) {
        element_ = null;
        onChanged();
      } else {
        element_ = null;
        elementBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .ServiceNameElement element = 2;</code>
     */
    public com.lyl.skywalking.proto.ServiceNameElement.Builder getElementBuilder() {

      onChanged();
      return getElementFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .ServiceNameElement element = 2;</code>
     */
    public com.lyl.skywalking.proto.ServiceNameElementOrBuilder getElementOrBuilder() {
      if (elementBuilder_ != null) {
        return elementBuilder_.getMessageOrBuilder();
      } else {
        return element_ == null ?
            com.lyl.skywalking.proto.ServiceNameElement.getDefaultInstance() : element_;
      }
    }
    /**
     * <code>optional .ServiceNameElement element = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.lyl.skywalking.proto.ServiceNameElement, com.lyl.skywalking.proto.ServiceNameElement.Builder, com.lyl.skywalking.proto.ServiceNameElementOrBuilder>
        getElementFieldBuilder() {
      if (elementBuilder_ == null) {
        elementBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.lyl.skywalking.proto.ServiceNameElement, com.lyl.skywalking.proto.ServiceNameElement.Builder, com.lyl.skywalking.proto.ServiceNameElementOrBuilder>(
                getElement(),
                getParentForChildren(),
                isClean());
        element_ = null;
      }
      return elementBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:ServiceNameMappingElement)
  }

  // @@protoc_insertion_point(class_scope:ServiceNameMappingElement)
  private static final com.lyl.skywalking.proto.ServiceNameMappingElement DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lyl.skywalking.proto.ServiceNameMappingElement();
  }

  public static com.lyl.skywalking.proto.ServiceNameMappingElement getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServiceNameMappingElement>
      PARSER = new com.google.protobuf.AbstractParser<ServiceNameMappingElement>() {
    public ServiceNameMappingElement parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new ServiceNameMappingElement(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<ServiceNameMappingElement> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ServiceNameMappingElement> getParserForType() {
    return PARSER;
  }

  public com.lyl.skywalking.proto.ServiceNameMappingElement getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

