// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DiscoveryService.proto

package com.lyl.skywalking.proto;

public interface ServiceNameCollectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServiceNameCollection)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ServiceNameElement elements = 1;</code>
   */
  java.util.List<ServiceNameElement>
      getElementsList();
  /**
   * <code>repeated .ServiceNameElement elements = 1;</code>
   */
  com.lyl.skywalking.proto.ServiceNameElement getElements(int index);
  /**
   * <code>repeated .ServiceNameElement elements = 1;</code>
   */
  int getElementsCount();
  /**
   * <code>repeated .ServiceNameElement elements = 1;</code>
   */
  java.util.List<? extends ServiceNameElementOrBuilder>
      getElementsOrBuilderList();
  /**
   * <code>repeated .ServiceNameElement elements = 1;</code>
   */
  com.lyl.skywalking.proto.ServiceNameElementOrBuilder getElementsOrBuilder(
          int index);
}
