// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TraceSegmentService.proto

package com.lyl.skywalking.proto;

/**
 * Protobuf enum {@code SpanLayer}
 */
public enum SpanLayer
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>Unknown = 0;</code>
   */
  Unknown(0, 0),
  /**
   * <code>Database = 1;</code>
   */
  Database(1, 1),
  /**
   * <code>RPCFramework = 2;</code>
   */
  RPCFramework(2, 2),
  /**
   * <code>Http = 3;</code>
   */
  Http(3, 3),
  /**
   * <code>MQ = 4;</code>
   */
  MQ(4, 4),
  UNRECOGNIZED(-1, -1),
  ;

  /**
   * <code>Unknown = 0;</code>
   */
  public static final int Unknown_VALUE = 0;
  /**
   * <code>Database = 1;</code>
   */
  public static final int Database_VALUE = 1;
  /**
   * <code>RPCFramework = 2;</code>
   */
  public static final int RPCFramework_VALUE = 2;
  /**
   * <code>Http = 3;</code>
   */
  public static final int Http_VALUE = 3;
  /**
   * <code>MQ = 4;</code>
   */
  public static final int MQ_VALUE = 4;


  public final int getNumber() {
    if (index == -1) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  public static SpanLayer valueOf(int value) {
    switch (value) {
      case 0: return Unknown;
      case 1: return Database;
      case 2: return RPCFramework;
      case 3: return Http;
      case 4: return MQ;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SpanLayer>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
          SpanLayer> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SpanLayer>() {
          public SpanLayer findValueByNumber(int number) {
            return SpanLayer.valueOf(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(index);
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.lyl.skywalking.proto.TraceSegmentServiceOuterClass.getDescriptor()
        .getEnumTypes().get(2);
  }

  private static final SpanLayer[] VALUES = values();

  public static SpanLayer valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int index;
  private final int value;

  private SpanLayer(int index, int value) {
    this.index = index;
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:SpanLayer)
}

