// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TraceSegmentService.proto

package com.lyl.skywalking.proto;

/**
 * Protobuf type {@code SpanObject}
 */
public  final class SpanObject extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:SpanObject)
    SpanObjectOrBuilder {
  // Use SpanObject.newBuilder() to construct.
  private SpanObject(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SpanObject() {
    spanId_ = 0;
    parentSpanId_ = 0;
    startTime_ = 0L;
    endTime_ = 0L;
    operationNameId_ = 0;
    operationName_ = "";
    peerId_ = 0;
    peer_ = "";
    spanType_ = 0;
    spanLayer_ = 0;
    componentId_ = 0;
    component_ = "";
    isError_ = false;
    tags_ = java.util.Collections.emptyList();
    logs_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SpanObject(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            spanId_ = input.readInt32();
            break;
          }
          case 16: {

            parentSpanId_ = input.readInt32();
            break;
          }
          case 24: {

            startTime_ = input.readInt64();
            break;
          }
          case 32: {

            endTime_ = input.readInt64();
            break;
          }
          case 40: {

            operationNameId_ = input.readInt32();
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            operationName_ = s;
            break;
          }
          case 56: {

            peerId_ = input.readInt32();
            break;
          }
          case 66: {
            String s = input.readStringRequireUtf8();

            peer_ = s;
            break;
          }
          case 72: {
            int rawValue = input.readEnum();

            spanType_ = rawValue;
            break;
          }
          case 80: {
            int rawValue = input.readEnum();

            spanLayer_ = rawValue;
            break;
          }
          case 88: {

            componentId_ = input.readInt32();
            break;
          }
          case 98: {
            String s = input.readStringRequireUtf8();

            component_ = s;
            break;
          }
          case 104: {

            isError_ = input.readBool();
            break;
          }
          case 114: {
            if (!((mutable_bitField0_ & 0x00002000) == 0x00002000)) {
              tags_ = new java.util.ArrayList<com.lyl.skywalking.proto.KeyWithStringValue>();
              mutable_bitField0_ |= 0x00002000;
            }
            tags_.add(input.readMessage(com.lyl.skywalking.proto.KeyWithStringValue.parser(), extensionRegistry));
            break;
          }
          case 122: {
            if (!((mutable_bitField0_ & 0x00004000) == 0x00004000)) {
              logs_ = new java.util.ArrayList<LogMessage>();
              mutable_bitField0_ |= 0x00004000;
            }
            logs_.add(input.readMessage(com.lyl.skywalking.proto.LogMessage.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      if (((mutable_bitField0_ & 0x00002000) == 0x00002000)) {
        tags_ = java.util.Collections.unmodifiableList(tags_);
      }
      if (((mutable_bitField0_ & 0x00004000) == 0x00004000)) {
        logs_ = java.util.Collections.unmodifiableList(logs_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lyl.skywalking.proto.TraceSegmentServiceOuterClass.internal_static_SpanObject_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lyl.skywalking.proto.TraceSegmentServiceOuterClass.internal_static_SpanObject_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lyl.skywalking.proto.SpanObject.class, com.lyl.skywalking.proto.SpanObject.Builder.class);
  }

  private int bitField0_;
  public static final int SPANID_FIELD_NUMBER = 1;
  private int spanId_;
  /**
   * <code>optional int32 spanId = 1;</code>
   */
  public int getSpanId() {
    return spanId_;
  }

  public static final int PARENTSPANID_FIELD_NUMBER = 2;
  private int parentSpanId_;
  /**
   * <code>optional int32 parentSpanId = 2;</code>
   */
  public int getParentSpanId() {
    return parentSpanId_;
  }

  public static final int STARTTIME_FIELD_NUMBER = 3;
  private long startTime_;
  /**
   * <code>optional int64 startTime = 3;</code>
   */
  public long getStartTime() {
    return startTime_;
  }

  public static final int ENDTIME_FIELD_NUMBER = 4;
  private long endTime_;
  /**
   * <code>optional int64 endTime = 4;</code>
   */
  public long getEndTime() {
    return endTime_;
  }

  public static final int OPERATIONNAMEID_FIELD_NUMBER = 5;
  private int operationNameId_;
  /**
   * <code>optional int32 operationNameId = 5;</code>
   */
  public int getOperationNameId() {
    return operationNameId_;
  }

  public static final int OPERATIONNAME_FIELD_NUMBER = 6;
  private volatile Object operationName_;
  /**
   * <code>optional string operationName = 6;</code>
   */
  public String getOperationName() {
    Object ref = operationName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      operationName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string operationName = 6;</code>
   */
  public com.google.protobuf.ByteString
      getOperationNameBytes() {
    Object ref = operationName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      operationName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PEERID_FIELD_NUMBER = 7;
  private int peerId_;
  /**
   * <code>optional int32 peerId = 7;</code>
   */
  public int getPeerId() {
    return peerId_;
  }

  public static final int PEER_FIELD_NUMBER = 8;
  private volatile Object peer_;
  /**
   * <code>optional string peer = 8;</code>
   */
  public String getPeer() {
    Object ref = peer_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      peer_ = s;
      return s;
    }
  }
  /**
   * <code>optional string peer = 8;</code>
   */
  public com.google.protobuf.ByteString
      getPeerBytes() {
    Object ref = peer_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      peer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SPANTYPE_FIELD_NUMBER = 9;
  private int spanType_;
  /**
   * <code>optional .SpanType spanType = 9;</code>
   */
  public int getSpanTypeValue() {
    return spanType_;
  }
  /**
   * <code>optional .SpanType spanType = 9;</code>
   */
  public com.lyl.skywalking.proto.SpanType getSpanType() {
    com.lyl.skywalking.proto.SpanType result = com.lyl.skywalking.proto.SpanType.valueOf(spanType_);
    return result == null ? com.lyl.skywalking.proto.SpanType.UNRECOGNIZED : result;
  }

  public static final int SPANLAYER_FIELD_NUMBER = 10;
  private int spanLayer_;
  /**
   * <code>optional .SpanLayer spanLayer = 10;</code>
   */
  public int getSpanLayerValue() {
    return spanLayer_;
  }
  /**
   * <code>optional .SpanLayer spanLayer = 10;</code>
   */
  public com.lyl.skywalking.proto.SpanLayer getSpanLayer() {
    com.lyl.skywalking.proto.SpanLayer result = com.lyl.skywalking.proto.SpanLayer.valueOf(spanLayer_);
    return result == null ? com.lyl.skywalking.proto.SpanLayer.UNRECOGNIZED : result;
  }

  public static final int COMPONENTID_FIELD_NUMBER = 11;
  private int componentId_;
  /**
   * <code>optional int32 componentId = 11;</code>
   */
  public int getComponentId() {
    return componentId_;
  }

  public static final int COMPONENT_FIELD_NUMBER = 12;
  private volatile Object component_;
  /**
   * <code>optional string component = 12;</code>
   */
  public String getComponent() {
    Object ref = component_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      component_ = s;
      return s;
    }
  }
  /**
   * <code>optional string component = 12;</code>
   */
  public com.google.protobuf.ByteString
      getComponentBytes() {
    Object ref = component_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      component_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISERROR_FIELD_NUMBER = 13;
  private boolean isError_;
  /**
   * <code>optional bool isError = 13;</code>
   */
  public boolean getIsError() {
    return isError_;
  }

  public static final int TAGS_FIELD_NUMBER = 14;
  private java.util.List<com.lyl.skywalking.proto.KeyWithStringValue> tags_;
  /**
   * <code>repeated .KeyWithStringValue tags = 14;</code>
   */
  public java.util.List<com.lyl.skywalking.proto.KeyWithStringValue> getTagsList() {
    return tags_;
  }
  /**
   * <code>repeated .KeyWithStringValue tags = 14;</code>
   */
  public java.util.List<? extends com.lyl.skywalking.proto.KeyWithStringValueOrBuilder>
      getTagsOrBuilderList() {
    return tags_;
  }
  /**
   * <code>repeated .KeyWithStringValue tags = 14;</code>
   */
  public int getTagsCount() {
    return tags_.size();
  }
  /**
   * <code>repeated .KeyWithStringValue tags = 14;</code>
   */
  public com.lyl.skywalking.proto.KeyWithStringValue getTags(int index) {
    return tags_.get(index);
  }
  /**
   * <code>repeated .KeyWithStringValue tags = 14;</code>
   */
  public com.lyl.skywalking.proto.KeyWithStringValueOrBuilder getTagsOrBuilder(
      int index) {
    return tags_.get(index);
  }

  public static final int LOGS_FIELD_NUMBER = 15;
  private java.util.List<LogMessage> logs_;
  /**
   * <code>repeated .LogMessage logs = 15;</code>
   */
  public java.util.List<LogMessage> getLogsList() {
    return logs_;
  }
  /**
   * <code>repeated .LogMessage logs = 15;</code>
   */
  public java.util.List<? extends com.lyl.skywalking.proto.LogMessageOrBuilder>
      getLogsOrBuilderList() {
    return logs_;
  }
  /**
   * <code>repeated .LogMessage logs = 15;</code>
   */
  public int getLogsCount() {
    return logs_.size();
  }
  /**
   * <code>repeated .LogMessage logs = 15;</code>
   */
  public com.lyl.skywalking.proto.LogMessage getLogs(int index) {
    return logs_.get(index);
  }
  /**
   * <code>repeated .LogMessage logs = 15;</code>
   */
  public com.lyl.skywalking.proto.LogMessageOrBuilder getLogsOrBuilder(
      int index) {
    return logs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (spanId_ != 0) {
      output.writeInt32(1, spanId_);
    }
    if (parentSpanId_ != 0) {
      output.writeInt32(2, parentSpanId_);
    }
    if (startTime_ != 0L) {
      output.writeInt64(3, startTime_);
    }
    if (endTime_ != 0L) {
      output.writeInt64(4, endTime_);
    }
    if (operationNameId_ != 0) {
      output.writeInt32(5, operationNameId_);
    }
    if (!getOperationNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, operationName_);
    }
    if (peerId_ != 0) {
      output.writeInt32(7, peerId_);
    }
    if (!getPeerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, peer_);
    }
    if (spanType_ != com.lyl.skywalking.proto.SpanType.Entry.getNumber()) {
      output.writeEnum(9, spanType_);
    }
    if (spanLayer_ != com.lyl.skywalking.proto.SpanLayer.Unknown.getNumber()) {
      output.writeEnum(10, spanLayer_);
    }
    if (componentId_ != 0) {
      output.writeInt32(11, componentId_);
    }
    if (!getComponentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 12, component_);
    }
    if (isError_ != false) {
      output.writeBool(13, isError_);
    }
    for (int i = 0; i < tags_.size(); i++) {
      output.writeMessage(14, tags_.get(i));
    }
    for (int i = 0; i < logs_.size(); i++) {
      output.writeMessage(15, logs_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (spanId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, spanId_);
    }
    if (parentSpanId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, parentSpanId_);
    }
    if (startTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, startTime_);
    }
    if (endTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, endTime_);
    }
    if (operationNameId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, operationNameId_);
    }
    if (!getOperationNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, operationName_);
    }
    if (peerId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, peerId_);
    }
    if (!getPeerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, peer_);
    }
    if (spanType_ != com.lyl.skywalking.proto.SpanType.Entry.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(9, spanType_);
    }
    if (spanLayer_ != com.lyl.skywalking.proto.SpanLayer.Unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(10, spanLayer_);
    }
    if (componentId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, componentId_);
    }
    if (!getComponentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(12, component_);
    }
    if (isError_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(13, isError_);
    }
    for (int i = 0; i < tags_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(14, tags_.get(i));
    }
    for (int i = 0; i < logs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(15, logs_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.lyl.skywalking.proto.SpanObject parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lyl.skywalking.proto.SpanObject parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.SpanObject parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lyl.skywalking.proto.SpanObject parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.SpanObject parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.lyl.skywalking.proto.SpanObject parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.SpanObject parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.lyl.skywalking.proto.SpanObject parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.SpanObject parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.lyl.skywalking.proto.SpanObject parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lyl.skywalking.proto.SpanObject prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SpanObject}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SpanObject)
      com.lyl.skywalking.proto.SpanObjectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lyl.skywalking.proto.TraceSegmentServiceOuterClass.internal_static_SpanObject_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lyl.skywalking.proto.TraceSegmentServiceOuterClass.internal_static_SpanObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lyl.skywalking.proto.SpanObject.class, com.lyl.skywalking.proto.SpanObject.Builder.class);
    }

    // Construct using com.lyl.skywalking.proto.SpanObject.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getTagsFieldBuilder();
        getLogsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      spanId_ = 0;

      parentSpanId_ = 0;

      startTime_ = 0L;

      endTime_ = 0L;

      operationNameId_ = 0;

      operationName_ = "";

      peerId_ = 0;

      peer_ = "";

      spanType_ = 0;

      spanLayer_ = 0;

      componentId_ = 0;

      component_ = "";

      isError_ = false;

      if (tagsBuilder_ == null) {
        tags_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00002000);
      } else {
        tagsBuilder_.clear();
      }
      if (logsBuilder_ == null) {
        logs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00004000);
      } else {
        logsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lyl.skywalking.proto.TraceSegmentServiceOuterClass.internal_static_SpanObject_descriptor;
    }

    public com.lyl.skywalking.proto.SpanObject getDefaultInstanceForType() {
      return com.lyl.skywalking.proto.SpanObject.getDefaultInstance();
    }

    public com.lyl.skywalking.proto.SpanObject build() {
      com.lyl.skywalking.proto.SpanObject result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.lyl.skywalking.proto.SpanObject buildPartial() {
      com.lyl.skywalking.proto.SpanObject result = new com.lyl.skywalking.proto.SpanObject(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.spanId_ = spanId_;
      result.parentSpanId_ = parentSpanId_;
      result.startTime_ = startTime_;
      result.endTime_ = endTime_;
      result.operationNameId_ = operationNameId_;
      result.operationName_ = operationName_;
      result.peerId_ = peerId_;
      result.peer_ = peer_;
      result.spanType_ = spanType_;
      result.spanLayer_ = spanLayer_;
      result.componentId_ = componentId_;
      result.component_ = component_;
      result.isError_ = isError_;
      if (tagsBuilder_ == null) {
        if (((bitField0_ & 0x00002000) == 0x00002000)) {
          tags_ = java.util.Collections.unmodifiableList(tags_);
          bitField0_ = (bitField0_ & ~0x00002000);
        }
        result.tags_ = tags_;
      } else {
        result.tags_ = tagsBuilder_.build();
      }
      if (logsBuilder_ == null) {
        if (((bitField0_ & 0x00004000) == 0x00004000)) {
          logs_ = java.util.Collections.unmodifiableList(logs_);
          bitField0_ = (bitField0_ & ~0x00004000);
        }
        result.logs_ = logs_;
      } else {
        result.logs_ = logsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lyl.skywalking.proto.SpanObject) {
        return mergeFrom((com.lyl.skywalking.proto.SpanObject)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lyl.skywalking.proto.SpanObject other) {
      if (other == com.lyl.skywalking.proto.SpanObject.getDefaultInstance()) return this;
      if (other.getSpanId() != 0) {
        setSpanId(other.getSpanId());
      }
      if (other.getParentSpanId() != 0) {
        setParentSpanId(other.getParentSpanId());
      }
      if (other.getStartTime() != 0L) {
        setStartTime(other.getStartTime());
      }
      if (other.getEndTime() != 0L) {
        setEndTime(other.getEndTime());
      }
      if (other.getOperationNameId() != 0) {
        setOperationNameId(other.getOperationNameId());
      }
      if (!other.getOperationName().isEmpty()) {
        operationName_ = other.operationName_;
        onChanged();
      }
      if (other.getPeerId() != 0) {
        setPeerId(other.getPeerId());
      }
      if (!other.getPeer().isEmpty()) {
        peer_ = other.peer_;
        onChanged();
      }
      if (other.spanType_ != 0) {
        setSpanTypeValue(other.getSpanTypeValue());
      }
      if (other.spanLayer_ != 0) {
        setSpanLayerValue(other.getSpanLayerValue());
      }
      if (other.getComponentId() != 0) {
        setComponentId(other.getComponentId());
      }
      if (!other.getComponent().isEmpty()) {
        component_ = other.component_;
        onChanged();
      }
      if (other.getIsError() != false) {
        setIsError(other.getIsError());
      }
      if (tagsBuilder_ == null) {
        if (!other.tags_.isEmpty()) {
          if (tags_.isEmpty()) {
            tags_ = other.tags_;
            bitField0_ = (bitField0_ & ~0x00002000);
          } else {
            ensureTagsIsMutable();
            tags_.addAll(other.tags_);
          }
          onChanged();
        }
      } else {
        if (!other.tags_.isEmpty()) {
          if (tagsBuilder_.isEmpty()) {
            tagsBuilder_.dispose();
            tagsBuilder_ = null;
            tags_ = other.tags_;
            bitField0_ = (bitField0_ & ~0x00002000);
            tagsBuilder_ =
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getTagsFieldBuilder() : null;
          } else {
            tagsBuilder_.addAllMessages(other.tags_);
          }
        }
      }
      if (logsBuilder_ == null) {
        if (!other.logs_.isEmpty()) {
          if (logs_.isEmpty()) {
            logs_ = other.logs_;
            bitField0_ = (bitField0_ & ~0x00004000);
          } else {
            ensureLogsIsMutable();
            logs_.addAll(other.logs_);
          }
          onChanged();
        }
      } else {
        if (!other.logs_.isEmpty()) {
          if (logsBuilder_.isEmpty()) {
            logsBuilder_.dispose();
            logsBuilder_ = null;
            logs_ = other.logs_;
            bitField0_ = (bitField0_ & ~0x00004000);
            logsBuilder_ =
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getLogsFieldBuilder() : null;
          } else {
            logsBuilder_.addAllMessages(other.logs_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lyl.skywalking.proto.SpanObject parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lyl.skywalking.proto.SpanObject) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int spanId_ ;
    /**
     * <code>optional int32 spanId = 1;</code>
     */
    public int getSpanId() {
      return spanId_;
    }
    /**
     * <code>optional int32 spanId = 1;</code>
     */
    public Builder setSpanId(int value) {

      spanId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 spanId = 1;</code>
     */
    public Builder clearSpanId() {

      spanId_ = 0;
      onChanged();
      return this;
    }

    private int parentSpanId_ ;
    /**
     * <code>optional int32 parentSpanId = 2;</code>
     */
    public int getParentSpanId() {
      return parentSpanId_;
    }
    /**
     * <code>optional int32 parentSpanId = 2;</code>
     */
    public Builder setParentSpanId(int value) {

      parentSpanId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 parentSpanId = 2;</code>
     */
    public Builder clearParentSpanId() {

      parentSpanId_ = 0;
      onChanged();
      return this;
    }

    private long startTime_ ;
    /**
     * <code>optional int64 startTime = 3;</code>
     */
    public long getStartTime() {
      return startTime_;
    }
    /**
     * <code>optional int64 startTime = 3;</code>
     */
    public Builder setStartTime(long value) {

      startTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 startTime = 3;</code>
     */
    public Builder clearStartTime() {

      startTime_ = 0L;
      onChanged();
      return this;
    }

    private long endTime_ ;
    /**
     * <code>optional int64 endTime = 4;</code>
     */
    public long getEndTime() {
      return endTime_;
    }
    /**
     * <code>optional int64 endTime = 4;</code>
     */
    public Builder setEndTime(long value) {

      endTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 endTime = 4;</code>
     */
    public Builder clearEndTime() {

      endTime_ = 0L;
      onChanged();
      return this;
    }

    private int operationNameId_ ;
    /**
     * <code>optional int32 operationNameId = 5;</code>
     */
    public int getOperationNameId() {
      return operationNameId_;
    }
    /**
     * <code>optional int32 operationNameId = 5;</code>
     */
    public Builder setOperationNameId(int value) {

      operationNameId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 operationNameId = 5;</code>
     */
    public Builder clearOperationNameId() {

      operationNameId_ = 0;
      onChanged();
      return this;
    }

    private Object operationName_ = "";
    /**
     * <code>optional string operationName = 6;</code>
     */
    public String getOperationName() {
      Object ref = operationName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        operationName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string operationName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getOperationNameBytes() {
      Object ref = operationName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        operationName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string operationName = 6;</code>
     */
    public Builder setOperationName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      operationName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string operationName = 6;</code>
     */
    public Builder clearOperationName() {

      operationName_ = getDefaultInstance().getOperationName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string operationName = 6;</code>
     */
    public Builder setOperationNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      operationName_ = value;
      onChanged();
      return this;
    }

    private int peerId_ ;
    /**
     * <code>optional int32 peerId = 7;</code>
     */
    public int getPeerId() {
      return peerId_;
    }
    /**
     * <code>optional int32 peerId = 7;</code>
     */
    public Builder setPeerId(int value) {

      peerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 peerId = 7;</code>
     */
    public Builder clearPeerId() {

      peerId_ = 0;
      onChanged();
      return this;
    }

    private Object peer_ = "";
    /**
     * <code>optional string peer = 8;</code>
     */
    public String getPeer() {
      Object ref = peer_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        peer_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string peer = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPeerBytes() {
      Object ref = peer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        peer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string peer = 8;</code>
     */
    public Builder setPeer(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      peer_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string peer = 8;</code>
     */
    public Builder clearPeer() {

      peer_ = getDefaultInstance().getPeer();
      onChanged();
      return this;
    }
    /**
     * <code>optional string peer = 8;</code>
     */
    public Builder setPeerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      peer_ = value;
      onChanged();
      return this;
    }

    private int spanType_ = 0;
    /**
     * <code>optional .SpanType spanType = 9;</code>
     */
    public int getSpanTypeValue() {
      return spanType_;
    }
    /**
     * <code>optional .SpanType spanType = 9;</code>
     */
    public Builder setSpanTypeValue(int value) {
      spanType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .SpanType spanType = 9;</code>
     */
    public com.lyl.skywalking.proto.SpanType getSpanType() {
      com.lyl.skywalking.proto.SpanType result = com.lyl.skywalking.proto.SpanType.valueOf(spanType_);
      return result == null ? com.lyl.skywalking.proto.SpanType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .SpanType spanType = 9;</code>
     */
    public Builder setSpanType(com.lyl.skywalking.proto.SpanType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      spanType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .SpanType spanType = 9;</code>
     */
    public Builder clearSpanType() {

      spanType_ = 0;
      onChanged();
      return this;
    }

    private int spanLayer_ = 0;
    /**
     * <code>optional .SpanLayer spanLayer = 10;</code>
     */
    public int getSpanLayerValue() {
      return spanLayer_;
    }
    /**
     * <code>optional .SpanLayer spanLayer = 10;</code>
     */
    public Builder setSpanLayerValue(int value) {
      spanLayer_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .SpanLayer spanLayer = 10;</code>
     */
    public com.lyl.skywalking.proto.SpanLayer getSpanLayer() {
      com.lyl.skywalking.proto.SpanLayer result = com.lyl.skywalking.proto.SpanLayer.valueOf(spanLayer_);
      return result == null ? com.lyl.skywalking.proto.SpanLayer.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .SpanLayer spanLayer = 10;</code>
     */
    public Builder setSpanLayer(com.lyl.skywalking.proto.SpanLayer value) {
      if (value == null) {
        throw new NullPointerException();
      }

      spanLayer_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .SpanLayer spanLayer = 10;</code>
     */
    public Builder clearSpanLayer() {

      spanLayer_ = 0;
      onChanged();
      return this;
    }

    private int componentId_ ;
    /**
     * <code>optional int32 componentId = 11;</code>
     */
    public int getComponentId() {
      return componentId_;
    }
    /**
     * <code>optional int32 componentId = 11;</code>
     */
    public Builder setComponentId(int value) {

      componentId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 componentId = 11;</code>
     */
    public Builder clearComponentId() {

      componentId_ = 0;
      onChanged();
      return this;
    }

    private Object component_ = "";
    /**
     * <code>optional string component = 12;</code>
     */
    public String getComponent() {
      Object ref = component_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        component_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>optional string component = 12;</code>
     */
    public com.google.protobuf.ByteString
        getComponentBytes() {
      Object ref = component_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        component_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string component = 12;</code>
     */
    public Builder setComponent(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      component_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string component = 12;</code>
     */
    public Builder clearComponent() {

      component_ = getDefaultInstance().getComponent();
      onChanged();
      return this;
    }
    /**
     * <code>optional string component = 12;</code>
     */
    public Builder setComponentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      component_ = value;
      onChanged();
      return this;
    }

    private boolean isError_ ;
    /**
     * <code>optional bool isError = 13;</code>
     */
    public boolean getIsError() {
      return isError_;
    }
    /**
     * <code>optional bool isError = 13;</code>
     */
    public Builder setIsError(boolean value) {

      isError_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool isError = 13;</code>
     */
    public Builder clearIsError() {

      isError_ = false;
      onChanged();
      return this;
    }

    private java.util.List<com.lyl.skywalking.proto.KeyWithStringValue> tags_ =
      java.util.Collections.emptyList();
    private void ensureTagsIsMutable() {
      if (!((bitField0_ & 0x00002000) == 0x00002000)) {
        tags_ = new java.util.ArrayList<com.lyl.skywalking.proto.KeyWithStringValue>(tags_);
        bitField0_ |= 0x00002000;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.lyl.skywalking.proto.KeyWithStringValue, com.lyl.skywalking.proto.KeyWithStringValue.Builder, com.lyl.skywalking.proto.KeyWithStringValueOrBuilder> tagsBuilder_;

    /**
     * <code>repeated .KeyWithStringValue tags = 14;</code>
     */
    public java.util.List<com.lyl.skywalking.proto.KeyWithStringValue> getTagsList() {
      if (tagsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tags_);
      } else {
        return tagsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .KeyWithStringValue tags = 14;</code>
     */
    public int getTagsCount() {
      if (tagsBuilder_ == null) {
        return tags_.size();
      } else {
        return tagsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .KeyWithStringValue tags = 14;</code>
     */
    public com.lyl.skywalking.proto.KeyWithStringValue getTags(int index) {
      if (tagsBuilder_ == null) {
        return tags_.get(index);
      } else {
        return tagsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .KeyWithStringValue tags = 14;</code>
     */
    public Builder setTags(
        int index, com.lyl.skywalking.proto.KeyWithStringValue value) {
      if (tagsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTagsIsMutable();
        tags_.set(index, value);
        onChanged();
      } else {
        tagsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .KeyWithStringValue tags = 14;</code>
     */
    public Builder setTags(
        int index, com.lyl.skywalking.proto.KeyWithStringValue.Builder builderForValue) {
      if (tagsBuilder_ == null) {
        ensureTagsIsMutable();
        tags_.set(index, builderForValue.build());
        onChanged();
      } else {
        tagsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .KeyWithStringValue tags = 14;</code>
     */
    public Builder addTags(com.lyl.skywalking.proto.KeyWithStringValue value) {
      if (tagsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTagsIsMutable();
        tags_.add(value);
        onChanged();
      } else {
        tagsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .KeyWithStringValue tags = 14;</code>
     */
    public Builder addTags(
        int index, com.lyl.skywalking.proto.KeyWithStringValue value) {
      if (tagsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTagsIsMutable();
        tags_.add(index, value);
        onChanged();
      } else {
        tagsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .KeyWithStringValue tags = 14;</code>
     */
    public Builder addTags(
        com.lyl.skywalking.proto.KeyWithStringValue.Builder builderForValue) {
      if (tagsBuilder_ == null) {
        ensureTagsIsMutable();
        tags_.add(builderForValue.build());
        onChanged();
      } else {
        tagsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .KeyWithStringValue tags = 14;</code>
     */
    public Builder addTags(
        int index, com.lyl.skywalking.proto.KeyWithStringValue.Builder builderForValue) {
      if (tagsBuilder_ == null) {
        ensureTagsIsMutable();
        tags_.add(index, builderForValue.build());
        onChanged();
      } else {
        tagsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .KeyWithStringValue tags = 14;</code>
     */
    public Builder addAllTags(
        Iterable<? extends com.lyl.skywalking.proto.KeyWithStringValue> values) {
      if (tagsBuilder_ == null) {
        ensureTagsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tags_);
        onChanged();
      } else {
        tagsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .KeyWithStringValue tags = 14;</code>
     */
    public Builder clearTags() {
      if (tagsBuilder_ == null) {
        tags_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00002000);
        onChanged();
      } else {
        tagsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .KeyWithStringValue tags = 14;</code>
     */
    public Builder removeTags(int index) {
      if (tagsBuilder_ == null) {
        ensureTagsIsMutable();
        tags_.remove(index);
        onChanged();
      } else {
        tagsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .KeyWithStringValue tags = 14;</code>
     */
    public com.lyl.skywalking.proto.KeyWithStringValue.Builder getTagsBuilder(
        int index) {
      return getTagsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .KeyWithStringValue tags = 14;</code>
     */
    public com.lyl.skywalking.proto.KeyWithStringValueOrBuilder getTagsOrBuilder(
        int index) {
      if (tagsBuilder_ == null) {
        return tags_.get(index);  } else {
        return tagsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .KeyWithStringValue tags = 14;</code>
     */
    public java.util.List<? extends com.lyl.skywalking.proto.KeyWithStringValueOrBuilder>
         getTagsOrBuilderList() {
      if (tagsBuilder_ != null) {
        return tagsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tags_);
      }
    }
    /**
     * <code>repeated .KeyWithStringValue tags = 14;</code>
     */
    public com.lyl.skywalking.proto.KeyWithStringValue.Builder addTagsBuilder() {
      return getTagsFieldBuilder().addBuilder(
          com.lyl.skywalking.proto.KeyWithStringValue.getDefaultInstance());
    }
    /**
     * <code>repeated .KeyWithStringValue tags = 14;</code>
     */
    public com.lyl.skywalking.proto.KeyWithStringValue.Builder addTagsBuilder(
        int index) {
      return getTagsFieldBuilder().addBuilder(
          index, com.lyl.skywalking.proto.KeyWithStringValue.getDefaultInstance());
    }
    /**
     * <code>repeated .KeyWithStringValue tags = 14;</code>
     */
    public java.util.List<com.lyl.skywalking.proto.KeyWithStringValue.Builder>
         getTagsBuilderList() {
      return getTagsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.lyl.skywalking.proto.KeyWithStringValue, com.lyl.skywalking.proto.KeyWithStringValue.Builder, com.lyl.skywalking.proto.KeyWithStringValueOrBuilder>
        getTagsFieldBuilder() {
      if (tagsBuilder_ == null) {
        tagsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.lyl.skywalking.proto.KeyWithStringValue, com.lyl.skywalking.proto.KeyWithStringValue.Builder, com.lyl.skywalking.proto.KeyWithStringValueOrBuilder>(
                tags_,
                ((bitField0_ & 0x00002000) == 0x00002000),
                getParentForChildren(),
                isClean());
        tags_ = null;
      }
      return tagsBuilder_;
    }

    private java.util.List<LogMessage> logs_ =
      java.util.Collections.emptyList();
    private void ensureLogsIsMutable() {
      if (!((bitField0_ & 0x00004000) == 0x00004000)) {
        logs_ = new java.util.ArrayList<LogMessage>(logs_);
        bitField0_ |= 0x00004000;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.lyl.skywalking.proto.LogMessage, com.lyl.skywalking.proto.LogMessage.Builder, com.lyl.skywalking.proto.LogMessageOrBuilder> logsBuilder_;

    /**
     * <code>repeated .LogMessage logs = 15;</code>
     */
    public java.util.List<LogMessage> getLogsList() {
      if (logsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(logs_);
      } else {
        return logsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .LogMessage logs = 15;</code>
     */
    public int getLogsCount() {
      if (logsBuilder_ == null) {
        return logs_.size();
      } else {
        return logsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .LogMessage logs = 15;</code>
     */
    public com.lyl.skywalking.proto.LogMessage getLogs(int index) {
      if (logsBuilder_ == null) {
        return logs_.get(index);
      } else {
        return logsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .LogMessage logs = 15;</code>
     */
    public Builder setLogs(
        int index, com.lyl.skywalking.proto.LogMessage value) {
      if (logsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLogsIsMutable();
        logs_.set(index, value);
        onChanged();
      } else {
        logsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .LogMessage logs = 15;</code>
     */
    public Builder setLogs(
        int index, com.lyl.skywalking.proto.LogMessage.Builder builderForValue) {
      if (logsBuilder_ == null) {
        ensureLogsIsMutable();
        logs_.set(index, builderForValue.build());
        onChanged();
      } else {
        logsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LogMessage logs = 15;</code>
     */
    public Builder addLogs(com.lyl.skywalking.proto.LogMessage value) {
      if (logsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLogsIsMutable();
        logs_.add(value);
        onChanged();
      } else {
        logsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .LogMessage logs = 15;</code>
     */
    public Builder addLogs(
        int index, com.lyl.skywalking.proto.LogMessage value) {
      if (logsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLogsIsMutable();
        logs_.add(index, value);
        onChanged();
      } else {
        logsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .LogMessage logs = 15;</code>
     */
    public Builder addLogs(
        com.lyl.skywalking.proto.LogMessage.Builder builderForValue) {
      if (logsBuilder_ == null) {
        ensureLogsIsMutable();
        logs_.add(builderForValue.build());
        onChanged();
      } else {
        logsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LogMessage logs = 15;</code>
     */
    public Builder addLogs(
        int index, com.lyl.skywalking.proto.LogMessage.Builder builderForValue) {
      if (logsBuilder_ == null) {
        ensureLogsIsMutable();
        logs_.add(index, builderForValue.build());
        onChanged();
      } else {
        logsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .LogMessage logs = 15;</code>
     */
    public Builder addAllLogs(
        Iterable<? extends LogMessage> values) {
      if (logsBuilder_ == null) {
        ensureLogsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, logs_);
        onChanged();
      } else {
        logsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .LogMessage logs = 15;</code>
     */
    public Builder clearLogs() {
      if (logsBuilder_ == null) {
        logs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00004000);
        onChanged();
      } else {
        logsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .LogMessage logs = 15;</code>
     */
    public Builder removeLogs(int index) {
      if (logsBuilder_ == null) {
        ensureLogsIsMutable();
        logs_.remove(index);
        onChanged();
      } else {
        logsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .LogMessage logs = 15;</code>
     */
    public com.lyl.skywalking.proto.LogMessage.Builder getLogsBuilder(
        int index) {
      return getLogsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .LogMessage logs = 15;</code>
     */
    public com.lyl.skywalking.proto.LogMessageOrBuilder getLogsOrBuilder(
        int index) {
      if (logsBuilder_ == null) {
        return logs_.get(index);  } else {
        return logsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .LogMessage logs = 15;</code>
     */
    public java.util.List<? extends com.lyl.skywalking.proto.LogMessageOrBuilder>
         getLogsOrBuilderList() {
      if (logsBuilder_ != null) {
        return logsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(logs_);
      }
    }
    /**
     * <code>repeated .LogMessage logs = 15;</code>
     */
    public com.lyl.skywalking.proto.LogMessage.Builder addLogsBuilder() {
      return getLogsFieldBuilder().addBuilder(
          com.lyl.skywalking.proto.LogMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .LogMessage logs = 15;</code>
     */
    public com.lyl.skywalking.proto.LogMessage.Builder addLogsBuilder(
        int index) {
      return getLogsFieldBuilder().addBuilder(
          index, com.lyl.skywalking.proto.LogMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .LogMessage logs = 15;</code>
     */
    public java.util.List<LogMessage.Builder>
         getLogsBuilderList() {
      return getLogsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.lyl.skywalking.proto.LogMessage, com.lyl.skywalking.proto.LogMessage.Builder, com.lyl.skywalking.proto.LogMessageOrBuilder>
        getLogsFieldBuilder() {
      if (logsBuilder_ == null) {
        logsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.lyl.skywalking.proto.LogMessage, com.lyl.skywalking.proto.LogMessage.Builder, com.lyl.skywalking.proto.LogMessageOrBuilder>(
                logs_,
                ((bitField0_ & 0x00004000) == 0x00004000),
                getParentForChildren(),
                isClean());
        logs_ = null;
      }
      return logsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:SpanObject)
  }

  // @@protoc_insertion_point(class_scope:SpanObject)
  private static final com.lyl.skywalking.proto.SpanObject DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lyl.skywalking.proto.SpanObject();
  }

  public static com.lyl.skywalking.proto.SpanObject getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SpanObject>
      PARSER = new com.google.protobuf.AbstractParser<SpanObject>() {
    public SpanObject parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new SpanObject(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<SpanObject> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SpanObject> getParserForType() {
    return PARSER;
  }

  public com.lyl.skywalking.proto.SpanObject getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

