// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TraceSegmentService.proto

package com.lyl.skywalking.proto;

public interface SpanObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SpanObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 spanId = 1;</code>
   */
  int getSpanId();

  /**
   * <code>optional int32 parentSpanId = 2;</code>
   */
  int getParentSpanId();

  /**
   * <code>optional int64 startTime = 3;</code>
   */
  long getStartTime();

  /**
   * <code>optional int64 endTime = 4;</code>
   */
  long getEndTime();

  /**
   * <code>optional int32 operationNameId = 5;</code>
   */
  int getOperationNameId();

  /**
   * <code>optional string operationName = 6;</code>
   */
  String getOperationName();
  /**
   * <code>optional string operationName = 6;</code>
   */
  com.google.protobuf.ByteString
      getOperationNameBytes();

  /**
   * <code>optional int32 peerId = 7;</code>
   */
  int getPeerId();

  /**
   * <code>optional string peer = 8;</code>
   */
  String getPeer();
  /**
   * <code>optional string peer = 8;</code>
   */
  com.google.protobuf.ByteString
      getPeerBytes();

  /**
   * <code>optional .SpanType spanType = 9;</code>
   */
  int getSpanTypeValue();
  /**
   * <code>optional .SpanType spanType = 9;</code>
   */
  com.lyl.skywalking.proto.SpanType getSpanType();

  /**
   * <code>optional .SpanLayer spanLayer = 10;</code>
   */
  int getSpanLayerValue();
  /**
   * <code>optional .SpanLayer spanLayer = 10;</code>
   */
  com.lyl.skywalking.proto.SpanLayer getSpanLayer();

  /**
   * <code>optional int32 componentId = 11;</code>
   */
  int getComponentId();

  /**
   * <code>optional string component = 12;</code>
   */
  String getComponent();
  /**
   * <code>optional string component = 12;</code>
   */
  com.google.protobuf.ByteString
      getComponentBytes();

  /**
   * <code>optional bool isError = 13;</code>
   */
  boolean getIsError();

  /**
   * <code>repeated .KeyWithStringValue tags = 14;</code>
   */
  java.util.List<KeyWithStringValue>
      getTagsList();
  /**
   * <code>repeated .KeyWithStringValue tags = 14;</code>
   */
  com.lyl.skywalking.proto.KeyWithStringValue getTags(int index);
  /**
   * <code>repeated .KeyWithStringValue tags = 14;</code>
   */
  int getTagsCount();
  /**
   * <code>repeated .KeyWithStringValue tags = 14;</code>
   */
  java.util.List<? extends KeyWithStringValueOrBuilder>
      getTagsOrBuilderList();
  /**
   * <code>repeated .KeyWithStringValue tags = 14;</code>
   */
  com.lyl.skywalking.proto.KeyWithStringValueOrBuilder getTagsOrBuilder(
          int index);

  /**
   * <code>repeated .LogMessage logs = 15;</code>
   */
  java.util.List<LogMessage>
      getLogsList();
  /**
   * <code>repeated .LogMessage logs = 15;</code>
   */
  com.lyl.skywalking.proto.LogMessage getLogs(int index);
  /**
   * <code>repeated .LogMessage logs = 15;</code>
   */
  int getLogsCount();
  /**
   * <code>repeated .LogMessage logs = 15;</code>
   */
  java.util.List<? extends LogMessageOrBuilder>
      getLogsOrBuilderList();
  /**
   * <code>repeated .LogMessage logs = 15;</code>
   */
  com.lyl.skywalking.proto.LogMessageOrBuilder getLogsOrBuilder(
          int index);
}
