// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TraceSegmentService.proto

package com.lyl.skywalking.proto;

public final class TraceSegmentServiceOuterClass {
  private TraceSegmentServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_UpstreamSegment_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UpstreamSegment_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_UniqueId_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UniqueId_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_TraceSegmentObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TraceSegmentObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_TraceSegmentReference_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TraceSegmentReference_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_SpanObject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SpanObject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_LogMessage_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LogMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\031TraceSegmentService.proto\032\020Downstream." +
      "proto\032\030KeyWithStringValue.proto\"E\n\017Upstr" +
      "eamSegment\022!\n\016globalTraceIds\030\001 \003(\0132\t.Uni" +
      "queId\022\017\n\007segment\030\002 \001(\014\"\033\n\010UniqueId\022\017\n\007id" +
      "Parts\030\001 \003(\003\"\306\001\n\022TraceSegmentObject\022!\n\016tr" +
      "aceSegmentId\030\001 \001(\0132\t.UniqueId\022$\n\004refs\030\002 " +
      "\003(\0132\026.TraceSegmentReference\022\032\n\005spans\030\003 \003" +
      "(\0132\013.SpanObject\022\025\n\rapplicationId\030\004 \001(\005\022\035" +
      "\n\025applicationInstanceId\030\005 \001(\005\022\025\n\risSizeL" +
      "imited\030\006 \001(\010\"\322\002\n\025TraceSegmentReference\022\031",
      "\n\007refType\030\001 \001(\0162\010.RefType\022\'\n\024parentTrace" +
      "SegmentId\030\002 \001(\0132\t.UniqueId\022\024\n\014parentSpan" +
      "Id\030\003 \001(\005\022#\n\033parentApplicationInstanceId\030" +
      "\004 \001(\005\022\026\n\016networkAddress\030\005 \001(\t\022\030\n\020network" +
      "AddressId\030\006 \001(\005\022\"\n\032entryApplicationInsta" +
      "nceId\030\007 \001(\005\022\030\n\020entryServiceName\030\010 \001(\t\022\026\n" +
      "\016entryServiceId\030\t \001(\005\022\031\n\021parentServiceNa" +
      "me\030\n \001(\t\022\027\n\017parentServiceId\030\013 \001(\005\"\327\002\n\nSp" +
      "anObject\022\016\n\006spanId\030\001 \001(\005\022\024\n\014parentSpanId" +
      "\030\002 \001(\005\022\021\n\tstartTime\030\003 \001(\003\022\017\n\007endTime\030\004 \001",
      "(\003\022\027\n\017operationNameId\030\005 \001(\005\022\025\n\roperation" +
      "Name\030\006 \001(\t\022\016\n\006peerId\030\007 \001(\005\022\014\n\004peer\030\010 \001(\t" +
      "\022\033\n\010spanType\030\t \001(\0162\t.SpanType\022\035\n\tspanLay" +
      "er\030\n \001(\0162\n.SpanLayer\022\023\n\013componentId\030\013 \001(" +
      "\005\022\021\n\tcomponent\030\014 \001(\t\022\017\n\007isError\030\r \001(\010\022!\n" +
      "\004tags\030\016 \003(\0132\023.KeyWithStringValue\022\031\n\004logs" +
      "\030\017 \003(\0132\013.LogMessage\"=\n\nLogMessage\022\014\n\004tim" +
      "e\030\001 \001(\003\022!\n\004data\030\002 \003(\0132\023.KeyWithStringVal" +
      "ue*,\n\007RefType\022\020\n\014CrossProcess\020\000\022\017\n\013Cross" +
      "Thread\020\001**\n\010SpanType\022\t\n\005Entry\020\000\022\010\n\004Exit\020",
      "\001\022\t\n\005Local\020\002*J\n\tSpanLayer\022\013\n\007Unknown\020\000\022\014" +
      "\n\010Database\020\001\022\020\n\014RPCFramework\020\002\022\010\n\004Http\020\003" +
      "\022\006\n\002MQ\020\0042C\n\023TraceSegmentService\022,\n\007colle" +
      "ct\022\020.UpstreamSegment\032\013.Downstream\"\000(\001B\034\n" +
      "\030com.lyl.skywalking.protoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lyl.skywalking.proto.DownstreamOuterClass.getDescriptor(),
          com.lyl.skywalking.proto.KeyWithStringValueOuterClass.getDescriptor(),
        }, assigner);
    internal_static_UpstreamSegment_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UpstreamSegment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UpstreamSegment_descriptor,
        new String[] { "GlobalTraceIds", "Segment", });
    internal_static_UniqueId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UniqueId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UniqueId_descriptor,
        new String[] { "IdParts", });
    internal_static_TraceSegmentObject_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TraceSegmentObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TraceSegmentObject_descriptor,
        new String[] { "TraceSegmentId", "Refs", "Spans", "ApplicationId", "ApplicationInstanceId", "IsSizeLimited", });
    internal_static_TraceSegmentReference_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_TraceSegmentReference_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TraceSegmentReference_descriptor,
        new String[] { "RefType", "ParentTraceSegmentId", "ParentSpanId", "ParentApplicationInstanceId", "NetworkAddress", "NetworkAddressId", "EntryApplicationInstanceId", "EntryServiceName", "EntryServiceId", "ParentServiceName", "ParentServiceId", });
    internal_static_SpanObject_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SpanObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SpanObject_descriptor,
        new String[] { "SpanId", "ParentSpanId", "StartTime", "EndTime", "OperationNameId", "OperationName", "PeerId", "Peer", "SpanType", "SpanLayer", "ComponentId", "Component", "IsError", "Tags", "Logs", });
    internal_static_LogMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_LogMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LogMessage_descriptor,
        new String[] { "Time", "Data", });
    com.lyl.skywalking.proto.DownstreamOuterClass.getDescriptor();
    com.lyl.skywalking.proto.KeyWithStringValueOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
