// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TraceSegmentService.proto

package com.lyl.skywalking.proto;

public interface TraceSegmentReferenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TraceSegmentReference)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .RefType refType = 1;</code>
   */
  int getRefTypeValue();
  /**
   * <code>optional .RefType refType = 1;</code>
   */
  com.lyl.skywalking.proto.RefType getRefType();

  /**
   * <code>optional .UniqueId parentTraceSegmentId = 2;</code>
   */
  boolean hasParentTraceSegmentId();
  /**
   * <code>optional .UniqueId parentTraceSegmentId = 2;</code>
   */
  com.lyl.skywalking.proto.UniqueId getParentTraceSegmentId();
  /**
   * <code>optional .UniqueId parentTraceSegmentId = 2;</code>
   */
  com.lyl.skywalking.proto.UniqueIdOrBuilder getParentTraceSegmentIdOrBuilder();

  /**
   * <code>optional int32 parentSpanId = 3;</code>
   */
  int getParentSpanId();

  /**
   * <code>optional int32 parentApplicationInstanceId = 4;</code>
   */
  int getParentApplicationInstanceId();

  /**
   * <code>optional string networkAddress = 5;</code>
   */
  String getNetworkAddress();
  /**
   * <code>optional string networkAddress = 5;</code>
   */
  com.google.protobuf.ByteString
      getNetworkAddressBytes();

  /**
   * <code>optional int32 networkAddressId = 6;</code>
   */
  int getNetworkAddressId();

  /**
   * <code>optional int32 entryApplicationInstanceId = 7;</code>
   */
  int getEntryApplicationInstanceId();

  /**
   * <code>optional string entryServiceName = 8;</code>
   */
  String getEntryServiceName();
  /**
   * <code>optional string entryServiceName = 8;</code>
   */
  com.google.protobuf.ByteString
      getEntryServiceNameBytes();

  /**
   * <code>optional int32 entryServiceId = 9;</code>
   */
  int getEntryServiceId();

  /**
   * <code>optional string parentServiceName = 10;</code>
   */
  String getParentServiceName();
  /**
   * <code>optional string parentServiceName = 10;</code>
   */
  com.google.protobuf.ByteString
      getParentServiceNameBytes();

  /**
   * <code>optional int32 parentServiceId = 11;</code>
   */
  int getParentServiceId();
}
