// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TraceSegmentService.proto

package com.lyl.skywalking.proto;

public interface UniqueIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UniqueId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 idParts = 1;</code>
   */
  java.util.List<Long> getIdPartsList();
  /**
   * <code>repeated int64 idParts = 1;</code>
   */
  int getIdPartsCount();
  /**
   * <code>repeated int64 idParts = 1;</code>
   */
  long getIdParts(int index);
}
