// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TraceSegmentService.proto

package com.lyl.skywalking.proto;

/**
 * Protobuf type {@code UpstreamSegment}
 */
public  final class UpstreamSegment extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:UpstreamSegment)
        UpstreamSegmentOrBuilder {
  // Use UpstreamSegment.newBuilder() to construct.
  private UpstreamSegment(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UpstreamSegment() {
    globalTraceIds_ = java.util.Collections.emptyList();
    segment_ = com.google.protobuf.ByteString.EMPTY;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private UpstreamSegment(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              globalTraceIds_ = new java.util.ArrayList<UniqueId>();
              mutable_bitField0_ |= 0x00000001;
            }
            globalTraceIds_.add(input.readMessage(com.lyl.skywalking.proto.UniqueId.parser(), extensionRegistry));
            break;
          }
          case 18: {

            segment_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        globalTraceIds_ = java.util.Collections.unmodifiableList(globalTraceIds_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lyl.skywalking.proto.TraceSegmentServiceOuterClass.internal_static_UpstreamSegment_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lyl.skywalking.proto.TraceSegmentServiceOuterClass.internal_static_UpstreamSegment_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lyl.skywalking.proto.UpstreamSegment.class, com.lyl.skywalking.proto.UpstreamSegment.Builder.class);
  }

  private int bitField0_;
  public static final int GLOBALTRACEIDS_FIELD_NUMBER = 1;
  private java.util.List<UniqueId> globalTraceIds_;
  /**
   * <code>repeated .UniqueId globalTraceIds = 1;</code>
   */
  public java.util.List<UniqueId> getGlobalTraceIdsList() {
    return globalTraceIds_;
  }
  /**
   * <code>repeated .UniqueId globalTraceIds = 1;</code>
   */
  public java.util.List<? extends UniqueIdOrBuilder>
      getGlobalTraceIdsOrBuilderList() {
    return globalTraceIds_;
  }
  /**
   * <code>repeated .UniqueId globalTraceIds = 1;</code>
   */
  public int getGlobalTraceIdsCount() {
    return globalTraceIds_.size();
  }
  /**
   * <code>repeated .UniqueId globalTraceIds = 1;</code>
   */
  public com.lyl.skywalking.proto.UniqueId getGlobalTraceIds(int index) {
    return globalTraceIds_.get(index);
  }
  /**
   * <code>repeated .UniqueId globalTraceIds = 1;</code>
   */
  public com.lyl.skywalking.proto.UniqueIdOrBuilder getGlobalTraceIdsOrBuilder(
      int index) {
    return globalTraceIds_.get(index);
  }

  public static final int SEGMENT_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString segment_;
  /**
   * <code>optional bytes segment = 2;</code>
   *
   * <pre>
   * the byte array of TraceSegmentObject
   * </pre>
   */
  public com.google.protobuf.ByteString getSegment() {
    return segment_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < globalTraceIds_.size(); i++) {
      output.writeMessage(1, globalTraceIds_.get(i));
    }
    if (!segment_.isEmpty()) {
      output.writeBytes(2, segment_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < globalTraceIds_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, globalTraceIds_.get(i));
    }
    if (!segment_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, segment_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.lyl.skywalking.proto.UpstreamSegment parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lyl.skywalking.proto.UpstreamSegment parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.UpstreamSegment parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lyl.skywalking.proto.UpstreamSegment parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.UpstreamSegment parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.lyl.skywalking.proto.UpstreamSegment parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.UpstreamSegment parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.lyl.skywalking.proto.UpstreamSegment parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.lyl.skywalking.proto.UpstreamSegment parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.lyl.skywalking.proto.UpstreamSegment parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lyl.skywalking.proto.UpstreamSegment prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UpstreamSegment}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UpstreamSegment)
      com.lyl.skywalking.proto.UpstreamSegmentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lyl.skywalking.proto.TraceSegmentServiceOuterClass.internal_static_UpstreamSegment_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lyl.skywalking.proto.TraceSegmentServiceOuterClass.internal_static_UpstreamSegment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lyl.skywalking.proto.UpstreamSegment.class, com.lyl.skywalking.proto.UpstreamSegment.Builder.class);
    }

    // Construct using com.lyl.skywalking.proto.UpstreamSegment.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getGlobalTraceIdsFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (globalTraceIdsBuilder_ == null) {
        globalTraceIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        globalTraceIdsBuilder_.clear();
      }
      segment_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lyl.skywalking.proto.TraceSegmentServiceOuterClass.internal_static_UpstreamSegment_descriptor;
    }

    public com.lyl.skywalking.proto.UpstreamSegment getDefaultInstanceForType() {
      return com.lyl.skywalking.proto.UpstreamSegment.getDefaultInstance();
    }

    public com.lyl.skywalking.proto.UpstreamSegment build() {
      com.lyl.skywalking.proto.UpstreamSegment result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.lyl.skywalking.proto.UpstreamSegment buildPartial() {
      com.lyl.skywalking.proto.UpstreamSegment result = new com.lyl.skywalking.proto.UpstreamSegment(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (globalTraceIdsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          globalTraceIds_ = java.util.Collections.unmodifiableList(globalTraceIds_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.globalTraceIds_ = globalTraceIds_;
      } else {
        result.globalTraceIds_ = globalTraceIdsBuilder_.build();
      }
      result.segment_ = segment_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lyl.skywalking.proto.UpstreamSegment) {
        return mergeFrom((com.lyl.skywalking.proto.UpstreamSegment)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lyl.skywalking.proto.UpstreamSegment other) {
      if (other == com.lyl.skywalking.proto.UpstreamSegment.getDefaultInstance()) return this;
      if (globalTraceIdsBuilder_ == null) {
        if (!other.globalTraceIds_.isEmpty()) {
          if (globalTraceIds_.isEmpty()) {
            globalTraceIds_ = other.globalTraceIds_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureGlobalTraceIdsIsMutable();
            globalTraceIds_.addAll(other.globalTraceIds_);
          }
          onChanged();
        }
      } else {
        if (!other.globalTraceIds_.isEmpty()) {
          if (globalTraceIdsBuilder_.isEmpty()) {
            globalTraceIdsBuilder_.dispose();
            globalTraceIdsBuilder_ = null;
            globalTraceIds_ = other.globalTraceIds_;
            bitField0_ = (bitField0_ & ~0x00000001);
            globalTraceIdsBuilder_ =
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getGlobalTraceIdsFieldBuilder() : null;
          } else {
            globalTraceIdsBuilder_.addAllMessages(other.globalTraceIds_);
          }
        }
      }
      if (other.getSegment() != com.google.protobuf.ByteString.EMPTY) {
        setSegment(other.getSegment());
      }
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lyl.skywalking.proto.UpstreamSegment parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lyl.skywalking.proto.UpstreamSegment) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<UniqueId> globalTraceIds_ =
      java.util.Collections.emptyList();
    private void ensureGlobalTraceIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        globalTraceIds_ = new java.util.ArrayList<UniqueId>(globalTraceIds_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.lyl.skywalking.proto.UniqueId, com.lyl.skywalking.proto.UniqueId.Builder, com.lyl.skywalking.proto.UniqueIdOrBuilder> globalTraceIdsBuilder_;

    /**
     * <code>repeated .UniqueId globalTraceIds = 1;</code>
     */
    public java.util.List<UniqueId> getGlobalTraceIdsList() {
      if (globalTraceIdsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(globalTraceIds_);
      } else {
        return globalTraceIdsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .UniqueId globalTraceIds = 1;</code>
     */
    @Override
    public int getGlobalTraceIdsCount() {
      if (globalTraceIdsBuilder_ == null) {
        return globalTraceIds_.size();
      } else {
        return globalTraceIdsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .UniqueId globalTraceIds = 1;</code>
     */
    @Override
    public com.lyl.skywalking.proto.UniqueId getGlobalTraceIds(int index) {
      if (globalTraceIdsBuilder_ == null) {
        return globalTraceIds_.get(index);
      } else {
        return globalTraceIdsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .UniqueId globalTraceIds = 1;</code>
     */
    public Builder setGlobalTraceIds(
        int index, com.lyl.skywalking.proto.UniqueId value) {
      if (globalTraceIdsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGlobalTraceIdsIsMutable();
        globalTraceIds_.set(index, value);
        onChanged();
      } else {
        globalTraceIdsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .UniqueId globalTraceIds = 1;</code>
     */
    public Builder setGlobalTraceIds(
        int index, com.lyl.skywalking.proto.UniqueId.Builder builderForValue) {
      if (globalTraceIdsBuilder_ == null) {
        ensureGlobalTraceIdsIsMutable();
        globalTraceIds_.set(index, builderForValue.build());
        onChanged();
      } else {
        globalTraceIdsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UniqueId globalTraceIds = 1;</code>
     */
    public Builder addGlobalTraceIds(com.lyl.skywalking.proto.UniqueId value) {
      if (globalTraceIdsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGlobalTraceIdsIsMutable();
        globalTraceIds_.add(value);
        onChanged();
      } else {
        globalTraceIdsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .UniqueId globalTraceIds = 1;</code>
     */
    public Builder addGlobalTraceIds(
        int index, com.lyl.skywalking.proto.UniqueId value) {
      if (globalTraceIdsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGlobalTraceIdsIsMutable();
        globalTraceIds_.add(index, value);
        onChanged();
      } else {
        globalTraceIdsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .UniqueId globalTraceIds = 1;</code>
     */
    public Builder addGlobalTraceIds(
        com.lyl.skywalking.proto.UniqueId.Builder builderForValue) {
      if (globalTraceIdsBuilder_ == null) {
        ensureGlobalTraceIdsIsMutable();
        globalTraceIds_.add(builderForValue.build());
        onChanged();
      } else {
        globalTraceIdsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UniqueId globalTraceIds = 1;</code>
     */
    public Builder addGlobalTraceIds(
        int index, com.lyl.skywalking.proto.UniqueId.Builder builderForValue) {
      if (globalTraceIdsBuilder_ == null) {
        ensureGlobalTraceIdsIsMutable();
        globalTraceIds_.add(index, builderForValue.build());
        onChanged();
      } else {
        globalTraceIdsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UniqueId globalTraceIds = 1;</code>
     */
    public Builder addAllGlobalTraceIds(
        Iterable<? extends UniqueId> values) {
      if (globalTraceIdsBuilder_ == null) {
        ensureGlobalTraceIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, globalTraceIds_);
        onChanged();
      } else {
        globalTraceIdsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .UniqueId globalTraceIds = 1;</code>
     */
    public Builder clearGlobalTraceIds() {
      if (globalTraceIdsBuilder_ == null) {
        globalTraceIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        globalTraceIdsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .UniqueId globalTraceIds = 1;</code>
     */
    public Builder removeGlobalTraceIds(int index) {
      if (globalTraceIdsBuilder_ == null) {
        ensureGlobalTraceIdsIsMutable();
        globalTraceIds_.remove(index);
        onChanged();
      } else {
        globalTraceIdsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .UniqueId globalTraceIds = 1;</code>
     */
    public com.lyl.skywalking.proto.UniqueId.Builder getGlobalTraceIdsBuilder(
        int index) {
      return getGlobalTraceIdsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .UniqueId globalTraceIds = 1;</code>
     */
    public com.lyl.skywalking.proto.UniqueIdOrBuilder getGlobalTraceIdsOrBuilder(
        int index) {
      if (globalTraceIdsBuilder_ == null) {
        return globalTraceIds_.get(index);  } else {
        return globalTraceIdsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .UniqueId globalTraceIds = 1;</code>
     */
    public java.util.List<? extends UniqueIdOrBuilder>
         getGlobalTraceIdsOrBuilderList() {
      if (globalTraceIdsBuilder_ != null) {
        return globalTraceIdsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(globalTraceIds_);
      }
    }
    /**
     * <code>repeated .UniqueId globalTraceIds = 1;</code>
     */
    public com.lyl.skywalking.proto.UniqueId.Builder addGlobalTraceIdsBuilder() {
      return getGlobalTraceIdsFieldBuilder().addBuilder(
          com.lyl.skywalking.proto.UniqueId.getDefaultInstance());
    }
    /**
     * <code>repeated .UniqueId globalTraceIds = 1;</code>
     */
    public com.lyl.skywalking.proto.UniqueId.Builder addGlobalTraceIdsBuilder(
        int index) {
      return getGlobalTraceIdsFieldBuilder().addBuilder(
          index, com.lyl.skywalking.proto.UniqueId.getDefaultInstance());
    }
    /**
     * <code>repeated .UniqueId globalTraceIds = 1;</code>
     */
    public java.util.List<UniqueId.Builder>
         getGlobalTraceIdsBuilderList() {
      return getGlobalTraceIdsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.lyl.skywalking.proto.UniqueId, com.lyl.skywalking.proto.UniqueId.Builder, com.lyl.skywalking.proto.UniqueIdOrBuilder>
        getGlobalTraceIdsFieldBuilder() {
      if (globalTraceIdsBuilder_ == null) {
        globalTraceIdsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.lyl.skywalking.proto.UniqueId, com.lyl.skywalking.proto.UniqueId.Builder, com.lyl.skywalking.proto.UniqueIdOrBuilder>(
                globalTraceIds_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        globalTraceIds_ = null;
      }
      return globalTraceIdsBuilder_;
    }

    private com.google.protobuf.ByteString segment_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes segment = 2;</code>
     *
     * <pre>
     * the byte array of TraceSegmentObject
     * </pre>
     */
    public com.google.protobuf.ByteString getSegment() {
      return segment_;
    }
    /**
     * <code>optional bytes segment = 2;</code>
     *
     * <pre>
     * the byte array of TraceSegmentObject
     * </pre>
     */
    public Builder setSegment(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }

      segment_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes segment = 2;</code>
     *
     * <pre>
     * the byte array of TraceSegmentObject
     * </pre>
     */
    public Builder clearSegment() {

      segment_ = getDefaultInstance().getSegment();
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:UpstreamSegment)
  }

  // @@protoc_insertion_point(class_scope:UpstreamSegment)
  private static final com.lyl.skywalking.proto.UpstreamSegment DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lyl.skywalking.proto.UpstreamSegment();
  }

  public static com.lyl.skywalking.proto.UpstreamSegment getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpstreamSegment>
      PARSER = new com.google.protobuf.AbstractParser<UpstreamSegment>() {
    public UpstreamSegment parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new UpstreamSegment(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<UpstreamSegment> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<UpstreamSegment> getParserForType() {
    return PARSER;
  }

  public com.lyl.skywalking.proto.UpstreamSegment getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

