// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TraceSegmentService.proto

package com.lyl.skywalking.proto;

public interface UpstreamSegmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpstreamSegment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .UniqueId globalTraceIds = 1;</code>
   */
  java.util.List<UniqueId>
      getGlobalTraceIdsList();
  /**
   * <code>repeated .UniqueId globalTraceIds = 1;</code>
   */
  com.lyl.skywalking.proto.UniqueId getGlobalTraceIds(int index);
  /**
   * <code>repeated .UniqueId globalTraceIds = 1;</code>
   */
  int getGlobalTraceIdsCount();
  /**
   * <code>repeated .UniqueId globalTraceIds = 1;</code>
   */
  java.util.List<? extends com.lyl.skywalking.proto.UniqueIdOrBuilder>
      getGlobalTraceIdsOrBuilderList();
  /**
   * <code>repeated .UniqueId globalTraceIds = 1;</code>
   */
  com.lyl.skywalking.proto.UniqueIdOrBuilder getGlobalTraceIdsOrBuilder(
          int index);

  /**
   * <code>optional bytes segment = 2;</code>
   *
   * <pre>
   * the byte array of TraceSegmentObject
   * </pre>
   */
  com.google.protobuf.ByteString getSegment();
}
